[package]
name = "serai-test-task"
version = "0.1.0"
description = "Common test utilities for serai-task ContinuallyRan tasks"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/tests/task"
authors = ["Luke Parker <lukeparker5132@gmail.com>", "rafael_xmr <g.pi8ax@slmail.me>"]
edition = "2021"
rust-version = "1.85"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
serai-task = { path = "../../common/task" }
serai-env = { path = "../../common/env", version = "0.1.0" }
