[package]
name = "ciphersuite"
version = "0.4.2"
description = "Ciphersuites built around ff/group"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/crypto/ciphersuite"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["ciphersuite", "ff", "group"]
edition = "2021"
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
std-shims = { path = "../../common/std-shims", version = "0.1.4", default-features = false }

zeroize = { version = "^1.5", default-features = false, features = ["derive"] }
subtle = { version = "^2.4", default-features = false }

digest = { version = "0.11.0-rc.1", default-features = false }

ff = { version = "0.13", default-features = false, features = ["bits"] }
group = { version = "0.13", default-features = false }

[dev-dependencies]
hex = { version = "0.4", default-features = false, features = ["std"] }

ff-group-tests = { version = "0.13", path = "../ff-group-tests" }

[features]
alloc = ["zeroize/alloc", "digest/alloc", "ff/alloc"]
std = [
  "alloc",

  "std-shims/std",

  "zeroize/std",
  "subtle/std",

  "ff/std",
]

default = ["std"]
