[package]
name = "serai-genesis-liquidity-pallet"
version = "0.1.0"
description = "Genesis liquidity pallet for Serai"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/genesis-liquidity"
authors = ["Akil Demir <akildemir72@gmail.com>"]
edition = "2021"
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-machete]
ignored = ["scale"]

[lints]
workspace = true

[dependencies]
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }

frame-system = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "311aa66887309af7bf455b4fdfd1ab59e24deea7", default-features = false }
frame-support = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "311aa66887309af7bf455b4fdfd1ab59e24deea7", default-features = false }

sp-std = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "311aa66887309af7bf455b4fdfd1ab59e24deea7", default-features = false }
sp-core = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "311aa66887309af7bf455b4fdfd1ab59e24deea7", default-features = false }
sp-application-crypto = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "311aa66887309af7bf455b4fdfd1ab59e24deea7", default-features = false }

dex-pallet = { package = "serai-dex-pallet", path = "../dex", default-features = false }
coins-pallet = { package = "serai-coins-pallet", path = "../coins", default-features = false }
validator-sets-pallet = { package = "serai-validator-sets-pallet", path = "../validator-sets", default-features = false }

economic-security-pallet = { package = "serai-economic-security-pallet", path = "../economic-security", default-features = false }

serai-primitives = { path = "../primitives", default-features = false }

[features]
std = [
  "scale/std",

  "frame-system/std",
  "frame-support/std",

  "sp-std/std",
  "sp-core/std",
  "sp-application-crypto/std",

  "coins-pallet/std",
  "dex-pallet/std",
  "validator-sets-pallet/std",

  "economic-security-pallet/std",

  "serai-primitives/std",
]
try-runtime = [] # TODO

default = ["std"]
