[package]
name = "serai-primitives"
version = "0.1.0"
description = "Primitives for the Serai blockchain"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/primitives"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
zeroize = { version = "^1.5", features = ["derive"] }
borsh = { version = "1", default-features = false, features = ["derive", "de_strict_order"] }

bitvec = { version = "1", default-features = false, features = ["alloc"] }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"], optional = true }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }
sp-core = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ece373ca1e8aaee67844eebcca28b5e016136dba", default-features = false }

ciphersuite = { path = "../../crypto/ciphersuite", default-features = false, features = ["alloc"] }
schnorr-signatures = { path = "../../crypto/schnorr", default-features = false }
dalek-ff-group = { path = "../../crypto/dalek-ff-group", default-features = false, features = ["alloc"] }
embedwards25519 = { path = "../../crypto/embedwards25519", default-features = false, features = ["alloc"] }
secq256k1 = { path = "../../crypto/secq256k1", default-features = false, features = ["alloc"] }
dkg = { package = "dkg-musig", path = "../../crypto/dkg/musig", default-features = false }

schnorrkel = { version = "0.11", default-features = false }

bech32 = { version = "0.11", default-features = false }

[dev-dependencies]
rand_core = { version = "0.6", default-features = false, features = ["std"] }

[features]
std = [
  "zeroize/std",
  "borsh/std",
  "bitvec/std",
  "scale?/std",
  "scale-info?/std",
  "sp-core/std",
  "ciphersuite/std",
  "schnorr-signatures/std",
  "dalek-ff-group/std",
  "embedwards25519/std",
  "secq256k1/std",
  "dkg/std",
  "schnorrkel/std",
  "bech32/std"
]
serde = []
non_canonical_scale_derivations = ["scale", "scale-info"]
default = ["std"]
