[package]
name = "serai-core-pallet"
version = "0.1.0"
description = "Core pallet"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/core"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
borsh = { version = "1", default-features = false, features = ["derive", "de_strict_order"] }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }

sp-core = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "e01101b68c5b0f588dd4cdee48f801a2c1f75b84", default-features = false }

frame-system = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "e01101b68c5b0f588dd4cdee48f801a2c1f75b84", default-features = false }
frame-support = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "e01101b68c5b0f588dd4cdee48f801a2c1f75b84", default-features = false }

pallet-timestamp = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "e01101b68c5b0f588dd4cdee48f801a2c1f75b84", default-features = false }

serai-abi = { path = "../abi", default-features = false, features = ["substrate"] }

[features]
std = [
  "borsh/std",
  "scale/std",

  "sp-core/std",

  "frame-system/std",
  "frame-support/std",

  "pallet-timestamp/std",

  "serai-abi/std",
]

runtime-benchmarks = [
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
]

try-runtime = ["pallet-timestamp/try-runtime", "serai-abi/try-runtime"]

default = ["std"]
