[workspace]
resolver = "2"
members = [
  "common/std-shims",
  "common/zalloc",
  "common/patchable-async-sleep",
  "common/db",
  "common/env",
  "common/task",
  "common/request",

  "crypto/transcript",

  "crypto/ff-group-tests",
  "crypto/dalek-ff-group",
  "crypto/ed448",
  "crypto/ciphersuite",
  "crypto/ciphersuite/kp256",

  "crypto/multiexp",
  "crypto/schnorr",

  "crypto/prime-field",
  "crypto/short-weierstrass",
  "crypto/secq256k1",
  "crypto/embedwards25519",

  "crypto/dkg",
  "crypto/dkg/recovery",
  "crypto/dkg/dealer",
  "crypto/dkg/musig",
  "crypto/dkg/evrf",
  "crypto/frost",
  "crypto/schnorrkel",

  "networks/bitcoin",

  "networks/ethereum/build-contracts",
  "networks/ethereum/schnorr",
  "networks/ethereum/alloy-simple-request-transport",
  "networks/ethereum/relayer",

  "message-queue",

  "processor/messages",

  "processor/key-gen",
  "processor/view-keys",
  "processor/frost-attempt-manager",

  "processor/primitives",
  "processor/scanner",
  "processor/scheduler/primitives",
  "processor/scheduler/utxo/primitives",
  "processor/scheduler/utxo/standard",
  "processor/scheduler/utxo/transaction-chaining",
  "processor/scheduler/smart-contract",
  "processor/signers",

  "processor/bin",
  "processor/bitcoin",
  "processor/ethereum/primitives",
  "processor/ethereum/test-primitives",
  "processor/ethereum/deployer",
  "processor/ethereum/erc20",
  "processor/ethereum/router",
  "processor/ethereum",
  "processor/monero",

  "coordinator/tributary-sdk/tendermint",
  "coordinator/tributary-sdk",
  "coordinator/cosign/types",
  "coordinator/cosign",
  "coordinator/substrate",
  "coordinator/tributary",
  "coordinator/p2p",
  "coordinator/p2p/libp2p",
  "coordinator",

  "substrate/primitives",
  "substrate/abi",

  "substrate/median",

  "substrate/core",
  "substrate/coins",
  "substrate/validator-sets",
  "substrate/signals",
  "substrate/dex",
  "substrate/genesis-liquidity",
  "substrate/economic-security",
  "substrate/emissions",
  "substrate/in-instructions",

  "substrate/runtime",
  "substrate/node",

  "substrate/client/serai",
  "substrate/client/bitcoin",
  "substrate/client/ethereum",
  "substrate/client/monero",
  "substrate/client",

  "orchestration",

  "mini",

  "tests/no-std",

  "tests/docker",
  "tests/message-queue",
  # TODO "tests/processor",
  # TODO "tests/coordinator",
  "tests/substrate",
  # TODO "tests/full-stack",
  "tests/reproducible-runtime",
]

[profile.dev]
panic = "abort"
overflow-checks = true
[profile.release]
panic = "abort"
overflow-checks = true
# These do not respect the `panic` configuration value, so we don't provide them
[profile.test]
# panic = "abort" # https://github.com/rust-lang/issues/67650
overflow-checks = true
[profile.bench]
overflow-checks = true

[profile.dev.package]
# Always compile Monero (and a variety of dependencies) with optimizations due
# to the extensive operations required for Bulletproofs
subtle = { opt-level = 3 }

sha3 = { opt-level = 3 }
blake2 = { opt-level = 3 }

ff = { opt-level = 3 }
group = { opt-level = 3 }

crypto-bigint = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
dalek-ff-group = { opt-level = 3 }

multiexp = { opt-level = 3 }

monero-io = { opt-level = 3 }
monero-primitives = { opt-level = 3 }
monero-ed25519 = { opt-level = 3 }
monero-mlsag = { opt-level = 3 }
monero-clsag = { opt-level = 3 }
monero-borromean = { opt-level = 3 }
monero-bulletproofs-generators = { opt-level = 3 }
monero-bulletproofs = {opt-level = 3 }
monero-oxide = { opt-level = 3 }

# Always compile the eVRF DKG tree with optimizations as well
secp256k1 = { opt-level = 3 }
secq256k1 = { opt-level = 3 }
embedwards25519 = { opt-level = 3 }
generalized-bulletproofs = { opt-level = 3 }
generalized-bulletproofs-circuit-abstraction = { opt-level = 3 }
generalized-bulletproofs-ec-gadgets = { opt-level = 3 }

# revm also effectively requires being built with optimizations
revm = { opt-level = 3 }
revm-bytecode = { opt-level = 3 }
revm-context = { opt-level = 3 }
revm-context-interface = { opt-level = 3 }
revm-database = { opt-level = 3 }
revm-database-interface = { opt-level = 3 }
revm-handler = { opt-level = 3 }
revm-inspector = { opt-level = 3 }
revm-interpreter = { opt-level = 3 }
revm-precompile = { opt-level = 3 }
revm-primitives = { opt-level = 3 }
revm-state = { opt-level = 3 }

[patch.crates-io]
# Point to empty crates for crates unused within in our tree
alloy-eip2124 = { path = "patches/ethereum/alloy-eip2124" }
ark-ff-3 = { package = "ark-ff", path = "patches/ethereum/ark-ff-0.3" }
ark-ff-4 = { package = "ark-ff", path = "patches/ethereum/ark-ff-0.4" }
c-kzg = { path = "patches/ethereum/c-kzg" }
fastrlp-3 = { package = "fastrlp", path = "patches/ethereum/fastrlp-0.3" }
fastrlp-4 = { package = "fastrlp", path = "patches/ethereum/fastrlp-0.4" }
primitive-types-12 = { package = "primitive-types", path = "patches/ethereum/primitive-types-0.12" }
rapidhash = { path = "patches/ethereum/rapidhash" }
rlp = { path = "patches/ethereum/rlp" }
secp256k1-30 = { package = "secp256k1", path = "patches/ethereum/secp256k1-0.30" }

# Dependencies from monero-oxide which originate from within our own tree,  potentially shimmed to account for deviations since publishing
std-shims = { path = "patches/std-shims" }
simple-request = { path = "patches/simple-request" }
multiexp = { path = "crypto/multiexp" }
flexible-transcript = { path = "crypto/transcript" }
ciphersuite = { path = "patches/ciphersuite" }
dalek-ff-group = { path = "patches/dalek-ff-group" }
minimal-ed448 = { path = "crypto/ed448" }
modular-frost = { path = "crypto/frost" }

# Patches due to `std` now including the required functionality
is_terminal_polyfill = { path = "patches/is_terminal_polyfill" }
lazy_static = { path = "patches/lazy_static" }
# This has a non-deprecated `std` alternative since Rust's 2024 edition
home = { path = "patches/home" }

# Updates to the latest version
darling = { path = "patches/darling" }
thiserror = { path = "patches/thiserror" }

# directories-next was created because directories was unmaintained
# directories-next is now unmaintained while directories is maintained
# The directories author pulls in ridiculously pointless crates and prefers
# copyleft licenses
# The following two patches resolve everything
option-ext = { path = "patches/option-ext" }
directories-next = { path = "patches/directories-next" }

# Patch from a fork back to upstream
parity-bip39 = { path = "patches/parity-bip39" }

# Patch to include `FromUniformBytes<64>` over `Scalar`
k256 = { git = "https://github.com/kayabaNerve/elliptic-curves", rev = "4994c9ab163781a88cd4a49beae812a89a44e8c3" }
p256 = { git = "https://github.com/kayabaNerve/elliptic-curves", rev = "4994c9ab163781a88cd4a49beae812a89a44e8c3" }

[workspace.lints.rust]
# https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html
ambiguous_negative_literals = "warn"
# closure_returning_async_block = "warn" # TODO: Enable
deprecated_safe = "warn"
deref_into_dyn_supertrait = "warn"
explicit_outlives_requirements = "warn"
impl_trait_redundant_captures = "warn"
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
# missing_docs = "warn" # TODO: Enable
non_ascii_idents = "warn"
redundant_lifetimes = "warn"
single_use_lifetimes = "warn"
trivial_casts = "warn"
unit_bindings = "warn"
unsafe_attr_outside_unsafe = "warn"
# unused_crate_dependencies = "warn" # TODO: Enable, replacing `machete`
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"

[workspace.lints.clippy]
# Manually verified with a GitHub workflow
incompatible_msrv = "allow"
# `x % 2` is simple and straightforward
manual_is_multiple_of = "allow"
# `.unwrap_or(x)` unwraps to `x`. This lint then errors if `x == Default::default()`
# Wanting to unwrap to `x` does not mean the caller wants to unwrap to `Default::default()`.
# While this asserts the current value of `Default::default()`, it doesn't guarantee that value
# will remain the default moving forward, which risks the unwrapped value changing unexpectedly.
unwrap_or_default = "allow"
# `.map(f).unwrap_or(x)` is clearer than `.map_or(x, f)`.
map_unwrap_or = "allow"
# Explicit `continue`s can increase readability.
needless_continue = "allow"

# Enable the off-by-default lint categories, before disabling those we don't want
pedantic = { level = "warn", priority = -1 }
case_sensitive_file_extension_comparisons = "allow"
default_trait_access = "allow" # TODO: Revisit
doc_markdown = "allow" # TODO: deny
explicit_deref_methods = "allow"
if_not_else = "allow"
implicit_hasher = "allow" # TODO: deny
inconsistent_struct_constructor = "allow"
items_after_statements = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow" # TODO: Revisit
naive_bytecount = "allow" # We don't want a suggestion to add an external dependency
similar_names = "allow"
single_match_else = "allow" # TODO: Revisit
struct_excessive_bools = "allow" # TODO: Revisit
struct_field_names = "allow"
too_many_lines = "allow"
wildcard_imports = "allow"

style = { level = "warn", priority = -1 }
items_after_test_module = "allow"

# Cherry-pick lints from the `restrictions` group
alloc_instead_of_core = "warn"
as_conversions = "warn"
as_pointer_underscore = "warn"
as_underscore = "warn"
assertions_on_result_states = "warn"
cfg_not_test = "warn"
create_dir = "warn"
dbg_macro = "warn"
filetype_is_file = "warn"
float_arithmetic = "warn"
float_cmp_const = "warn"
fn_to_numeric_cast_any = "warn"
get_unwrap = "warn"
if_then_some_else_none = "warn"
# iter_over_hash_type = "warn" # TODO: Enable
lossy_float_literal = "warn"
# partial_pub_fields = "warn" # TODO: Revisit
precedence_bits = "warn"
rc_mutex = "warn"
# redundant_test_prefix = "warn" # TODO: Enable
same_name_method = "warn"
std_instead_of_alloc = "warn"
std_instead_of_core = "warn"
str_to_string = "warn"
string_slice = "warn"
suspicious_xor_used_as_pow = "warn"
# todo = "warn" # TODO: Enable
unnecessary_self_imports = "warn"
# unused_trait_names = "warn" # TODO: Enable
wildcard_enum_match_arm = "warn"
