# syntax=docker/dockerfile:1
# check=skip=FromPlatformFlagConstDisallowed;error=true
# We want to explicitly set the platform to ensure a constant host environment

# stagex/pallet-rust (2026.03.0)
FROM --platform=linux/amd64 stagex/pallet-rust@sha256:2fbe7b164dd92edb9c1096152f6d27592d8a69b1b8eb2fc907b5fadea7d11668 AS builder

# Add files for build
ADD patches /serai/patches
ADD common /serai/common
ADD crypto /serai/crypto
ADD networks /serai/networks
ADD message-queue /serai/message-queue
ADD processor /serai/processor
ADD coordinator /serai/coordinator
ADD substrate /serai/substrate
ADD orchestration/Cargo.toml /serai/orchestration/Cargo.toml
ADD orchestration/src /serai/orchestration/src
ADD tests /serai/tests
ADD Cargo.toml /serai
ADD Cargo.lock /serai
ADD AGPL-3.0 /serai

WORKDIR /serai

# Build the runtime
RUN cargo build --locked --release -p serai-runtime --no-default-features -vv
# Move it to the root
RUN mv $(find /serai -name serai_runtime.wasm | head -n1) /serai.wasm

# Copy the artifact to its own image which solely exists to further export it
# We don't use a StageX image here as we don't require reproducibility and want this to be native
# (StageX images are currently only available for x86-64)
FROM busybox:stable-musl
# Copy the artifact itself
COPY --from=builder /serai.wasm /
# By default, copy the artifact to `/volume`, presumably a provided volume
CMD ["cp", "/serai.wasm", "/volume/"]
