# syntax=docker/dockerfile:1
# check=skip=FromPlatformFlagConstDisallowed;error=true
# We want to explicitly set the platform to ensure a constant host environment

# rust:1.93.1-alpine3.23 as of February 13th, 2026 (GMT)
FROM --platform=linux/amd64 rust@sha256:2249050332b405613b17fa96bef438b9b92569d76b3e1f64cbb7fb603abb713d AS builder

# Add Rust's source, as necessary to `build-std` as we do for the WASM
RUN rustup component add rust-src

# Add files for build
ADD patches /serai/patches
ADD common /serai/common
ADD crypto /serai/crypto
ADD networks /serai/networks
ADD message-queue /serai/message-queue
ADD processor /serai/processor
ADD coordinator /serai/coordinator
ADD substrate /serai/substrate
ADD orchestration/Cargo.toml /serai/orchestration/Cargo.toml
ADD orchestration/src /serai/orchestration/src
ADD tests /serai/tests
ADD Cargo.toml /serai
ADD Cargo.lock /serai
ADD AGPL-3.0 /serai

WORKDIR /serai

# Build the runtime
RUN cargo build --locked --release -p serai-runtime --no-default-features -vv
# Move it to the root
RUN mv $(find /serai -name serai_runtime.wasm | head -n1) /serai.wasm

# Copy the artifact to its own image which solely exists to further export it
# We don't use a platform-pin here as we don't require reproducibility and want this to be native
FROM alpine:latest
# Copy the artifact itself
COPY --from=builder /serai.wasm /
# By default, copy the artifact to `/volume`, presumably a provided volume
CMD ["cp", "/serai.wasm", "/volume/"]
