[package]
name = "serai-validator-sets-pallet"
version = "0.1.0"
description = "Validator sets pallet"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/validator-sets"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
bitvec = { version = "1", default-features = false, features = ["alloc", "serde"] }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "bit-vec"] }

sp-core = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "5d194a8965b1ce24bac0ece84bae5ad05c30fffb", default-features = false }
sp-application-crypto = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "5d194a8965b1ce24bac0ece84bae5ad05c30fffb", default-features = false }
sp-io = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "5d194a8965b1ce24bac0ece84bae5ad05c30fffb", default-features = false }
sp-api = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "5d194a8965b1ce24bac0ece84bae5ad05c30fffb", default-features = false }

frame-system = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "5d194a8965b1ce24bac0ece84bae5ad05c30fffb", default-features = false }
frame-support = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "5d194a8965b1ce24bac0ece84bae5ad05c30fffb", default-features = false }

pallet-session = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "5d194a8965b1ce24bac0ece84bae5ad05c30fffb", default-features = false }
pallet-babe = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "5d194a8965b1ce24bac0ece84bae5ad05c30fffb", default-features = false }
pallet-grandpa = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "5d194a8965b1ce24bac0ece84bae5ad05c30fffb", default-features = false }

serai-abi = { path = "../abi", default-features = false, features = ["substrate"] }

serai-core-pallet = { path = "../core", default-features = false }
serai-coins-pallet = { path = "../coins", default-features = false }

[dev-dependencies]
zeroize = "^1.5"

rand_core = "0.6"

borsh = { version = "1", default-features = false, features = ["derive", "de_strict_order"] }

[features]
std = [
  "bitvec/std",

  "scale/std",

  "sp-core/std",
  "sp-application-crypto/std",
  "sp-io/std",
  "sp-api/std",

  "frame-system/std",
  "frame-support/std",

  "pallet-session/std",
  "pallet-babe/std",
  "pallet-grandpa/std",

  "serai-abi/std",

  "serai-core-pallet/std",
  "serai-coins-pallet/std",
]

try-runtime = [
  "serai-abi/try-runtime",

  "frame-system/try-runtime",
  "frame-support/try-runtime",

  "pallet-session/try-runtime",
  "pallet-babe/try-runtime",
  "pallet-grandpa/try-runtime",

  "serai-core-pallet/try-runtime",
  "serai-coins-pallet/try-runtime",
]

runtime-benchmarks = [
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",

  "pallet-babe/runtime-benchmarks",
  "pallet-grandpa/runtime-benchmarks",

  "serai-core-pallet/runtime-benchmarks",
  "serai-coins-pallet/runtime-benchmarks",
]

default = ["std"]
