[package]
name = "serai-node"
version = "0.1.0"
description = "Serai network node, built over Substrate"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/node"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
publish = false
rust-version = "1.74"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[[bin]]
name = "serai-node"

[dependencies]
rand_core = "0.6"
zeroize = "1"
hex = "0.4"
log = "0.4"

schnorrkel = "0.11"

libp2p = "0.52"

sp-core = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sp-keystore = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sp-timestamp = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sp-state-machine = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sp-io = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sp-blockchain = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sp-runtime = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sp-api = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sp-block-builder = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sp-consensus-babe = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }

frame-benchmarking = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }

serai-runtime = { path = "../runtime", features = ["std"] }

clap = { version = "4", features = ["derive"] }

futures-util = "0.3"
tokio = { version = "1", features = ["sync", "rt-multi-thread"] }
jsonrpsee = { version = "0.24", features = ["server"] }

sc-transaction-pool = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-transaction-pool-api = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-basic-authorship = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-executor = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-service = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-client-api = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-network = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }

sc-consensus = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-consensus-babe = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-consensus-grandpa = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-authority-discovery = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }

sc-telemetry = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-chain-spec = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
sc-cli = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }

frame-system-rpc-runtime-api = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
substrate-frame-rpc-system = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }
pallet-transaction-payment-rpc = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }

serai-env = { path = "../../common/env" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev =  "7f2a8865cd0ded35e1d62fc330915d44dfa3beab" }

[features]
default = []
fast-epoch = ["serai-runtime/fast-epoch"]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",

  "serai-runtime/runtime-benchmarks",
]
