[package]
name = "blake2b_simd"
version = "1.99.99"
description = "Patch blake2b_simd to blake2"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/patches/blake2b_simd"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace]

[dependencies]
blake2 = { version = "0.10", default-features = false }
