# Switch to a non-root user
RUN useradd --system --home /home/serai --shell /sbin/nologin serai
USER serai

WORKDIR /home/serai

# Copy the Serai binary and relevant license
COPY --from=builder --chown=serai /serai/bin/serai-node /bin/
COPY --from=builder --chown=serai /serai/AGPL-3.0 .

# Run node
EXPOSE 30333 9615 9933 9944
CMD ["serai-node"]
