[package]
name = "serai-no-std-tests"
version = "0.1.0"
description = "A crate to test no-std builds of Serai crates work"
license = "MIT"
repository = "https://github.com/kayabaNerve/serai/tree/develop/tests/no-std"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["nostd", "no_std", "alloc"]
edition = "2021"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
std-shims = { path = "../../common/std-shims", default-features = false }

flexible-transcript = { path = "../../crypto/transcript", default-features = false, features = ["recommended", "merlin"] }

multiexp = { path = "../../crypto/multiexp", default-features = false }

dalek-ff-group = { path = "../../crypto/dalek-ff-group", default-features = false }
minimal-ed448 = { path = "../../crypto/ed448", default-features = false }

ciphersuite = { path = "../../crypto/ciphersuite", default-features = false }

schnorr-signatures = { path = "../../crypto/schnorr", default-features = false }

prime-field = { path = "../../crypto/prime-field", default-features = false }
short-weierstrass = { path = "../../crypto/short-weierstrass", default-features = false }
secq256k1 = { path = "../../crypto/secq256k1", default-features = false }
embedwards25519 = { path = "../../crypto/embedwards25519", default-features = false }

dkg = { path = "../../crypto/dkg", default-features = false, optional = true }
dkg-dealer = { path = "../../crypto/dkg/dealer", default-features = false, optional = true }
dkg-recovery = { path = "../../crypto/dkg/recovery", default-features = false, optional = true }
dkg-musig = { path = "../../crypto/dkg/musig", default-features = false, optional = true }
dkg-evrf = { path = "../../crypto/dkg/evrf", default-features = false, features = ["secp256k1", "ed25519"], optional = true }

modular-frost = { path = "../../crypto/frost", default-features = false, optional = true }
frost-schnorrkel = { path = "../../crypto/schnorrkel", default-features = false, optional = true }

bitcoin-serai = { path = "../../networks/bitcoin", default-features = false, features = ["hazmat"], optional = true }

ethereum-schnorr-contract = { path = "../../networks/ethereum/schnorr", default-features = false }

[features]
alloc = [
  "std-shims/alloc",

  "multiexp/alloc",
  "multiexp/batch",

  "dalek-ff-group/alloc",
  "minimal-ed448/alloc",

  "ciphersuite/alloc",

  "schnorr-signatures/alloc",

  "prime-field/alloc",
  "short-weierstrass/alloc",
  "secq256k1/alloc",
  "embedwards25519/alloc",

  "dkg",
  "dkg-dealer",
  "dkg-recovery",
  "dkg-musig",
  "dkg-evrf",

  "modular-frost",
  "frost-schnorrkel",

  "bitcoin-serai",

  "ethereum-schnorr-contract/alloc",
]
