[package]
name = "ethereum"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
web3 = "0.17.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
hex-literal = "0.3"
actix-rt = "*"
ethers = { git = "https://github.com/gakonst/ethers-rs" }
eyre = "0.6"