name: docker
description: Installs `docker` for Serai

runs:
  using: "composite"
  steps:
    - name: Remove preinstalled Docker
      if: runner.os == 'Linux'
      shell: bash
      run: |
        docker system prune --all --force

        sudo apt remove -y *docker*

        # Install `uidmap`, required for the explicitly-installed rootless Docker
        sudo apt install -y uidmap

    - name: Install rootless Docker (Linux)
      uses: docker/setup-docker-action@e43656e248c0bd0647d3f5c195d116aacf6fcaf4 # 4.7.0
      if: runner.os == 'Linux'
      with:
        rootless: true
        set-host: true
        # https://github.com/moby/moby/issues/45014
        daemon-config: |
          {
            "exec-opts": ["native.cgroupdriver=cgroupfs"]
          }

    - name: Remove preinstalled Docker
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # Docker isn't pre-installed on macOS images, so we solely have to confirm it isn't
        if [ $(command -v docker; printf $?) -eq 0 ]; then
          echo "\`docker`` was pre-installed"
          exit 1
        fi

    # This is notably faster than `-netdev user`, which Lima defaults to
    - name: Use `vmnet` for QEMU's networking driver
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # Install QEMU and `socat`, which we use to replicate `user,hostfwd`
        brew install qemu socat

        # Define a wrapper which replaces the network driver with `vmnet-shared`
        echo '#!/bin/sh

        # Using `vmnet-shared` requires elevated privileges, so we run with `sudo`
        QEMU="sudo qemu-system-aarch64"

        # Replace `-netdev user` with `-netdev vmnet-shared`
        NETDEV=0
        NETDEV_NEXT=0
        NETDEV_FWD_FROM=""
        NETDEV_FWD_TO=""
        for var in "$@"; do
          if [ $NETDEV_NEXT -eq 1 ]; then
            NETDEV_ID=$(printf "%s" "$var" | grep --only-matching ,id=[^,]*)
            NETDEV_ID=$(printf "%s" "$NETDEV_ID" | grep --only-matching [^=]*$)
            if [ ! "$NETDEV_ID" = "" ]; then
              NETDEV=1

              # Translate `dhcpstart`, the first of 16 addresses for DHCP, to `start-address`,
              # `end-address`, the `vmnet` options for a range of addresses to use for DHCP
              NETDEV_START=$(printf "%s" "$var" | grep --only-matching ,dhcpstart=[^,]*)
              NETDEV_START=$(printf "%s" "$NETDEV_START" | grep --only-matching [^=]*$)

              NETDEV_FIRST_THREE=$(printf "%s" "$NETDEV_START" | grep --only-matching ".*\.")
              NETDEV_END_FOURTH=$(( $(echo $NETDEV_START | grep --only-matching "[0-9]*$") + 16 ))
              NETDEV_END=$NETDEV_FIRST_THREE$NETDEV_END_FOURTH

              # The observable effects of macOS are that the starting IP is used for the gateway,
              # with the IPs assigned incrementally after that. So, for the one machine we spawn,
              # it will be assigned the IP following the gateway
              NETDEV_FIRST_IP_FOURTH=$(( $(echo $NETDEV_START | grep --only-matching "[0-9]*$") + 1 ))
              NETDEV_FIRST_IP=$NETDEV_FIRST_THREE$NETDEV_FIRST_IP_FOURTH

              NETDEV_FWD=$(printf "%s" "$var" | grep --only-matching ,hostfwd=[^,]*)
              NETDEV_FWD=$(printf "%s" "$NETDEV_FWD" | grep --only-matching [^=]*$)

              NETDEV_FWD_FROM=$(printf "%s" "$NETDEV_FWD" | grep --only-matching ^[^-]*)

              NETDEV_FWD_TO_PORT=$(printf "%s" "$NETDEV_FWD" | grep --only-matching [^-]*$)
              NETDEV_FWD_TO=tcp:$NETDEV_FIRST_IP$NETDEV_FWD_TO_PORT
              echo "Forwarding from $NETDEV_FWD_FROM to $NETDEV_FWD_TO"

              var="vmnet-shared,id=$NETDEV_ID,start-address=$NETDEV_START,end-address=$NETDEV_END,subnet-mask=255.255.255.0"
              echo "Using \`-netdev $var\`"
            fi
          fi
          NETDEV_NEXT=0

          if [ "$var" = "-netdev" ]; then
            NETDEV_NEXT=1
          fi

          QEMU="$QEMU $var"
        done

        if [ $NETDEV -eq 0 ]; then
          $QEMU
        else
          $QEMU &
          QEMU_PID=$!

          # Spawn `socat` to service socket connections for as long as QEMU is running
          NETDEV_FWD_FROM_PORT=$(printf "%s" "$NETDEV_FWD_FROM" | grep --only-matching [^:]*$)
          while [ $(kill -0 $QEMU_PID; printf "%i" $?) -eq 0 ]; do
            sudo socat $NETDEV_FWD_TO,nodelay,keepalive tcp4-listen:$NETDEV_FWD_FROM_PORT,nodelay,keepalive
            # This presumably means the machine has yet to listen on this port, so we `sleep` as to
            # not hammer the still-booting VM
            if [ $? -ne 0 ]; then
              sleep 10
            fi
          done
        fi
        ' > ./qemu-system-aarch64-vmnet
        chmod +x ./qemu-system-aarch64-vmnet

        # Install our wrapper to the same directory as QEMU
        # This is necessary as Lima assumes firmware files' locations relative to the executable's
        mv qemu-system-aarch64-vmnet $(which qemu-system-aarch64 | sed s/"\/"[^\/]*$//)

    - name: Install Docker (macOS)
      uses: docker/setup-docker-action@e43656e248c0bd0647d3f5c195d116aacf6fcaf4 # 4.7.0
      if: runner.os == 'macOS'
      env:
        # m1 chips, as seen in the GitHub CI, don't support nested hardware virtualization.
        #
        # We need `-machine virt` to stop Lima from providing `accel=hvf`due to this
        # [QEMU issue](https://gitlab.com/qemu-project/qemu/-/issues/2981).
        #
        # We also need `-cpu *` to stop Lima from providing `-cpu host` as:
        # 1) `-cpu host` requires `kvm` or `hvf` (which we don't have)
        # 2) `-cpu host` implies `host-phys-bits=on` which is borked in this environment
        # We choose `-cpu max` as the most reasonable option.
        #
        # Finally, for performance reasons (running Docker containers with `qemu-system-aarch64` as
        # our containerization solution, which then executes x86-64 binaries), we apply a myriad of
        # configuration options.
        #
        # While we use `-cpu max`, we disable `pmu` (performance monitoring) as unnecessary, large
        # vector instructions (to simplify the emulated CPU), `sme` (matrix instructions) for the
        # same reason, and `pauth` (memory authentication) for a notable performance benefit.
        #
        # We limit to 3 GB of RAM, as our processes should not require a notable amount of RAM.
        # As we cannot use the `hvf` accelerator, it isn't an issue to specify the default `tcg`
        # accelerator, and we do so to provide it with a massive cache. While it defaults to 1 GB,
        # we use 2 GB (specified in MiB) to maximize our performance. In total, this leaves 2 GB of
        # RAM for macOS itself (as the runner has 7 GB).
        #
        # We also specify no graphics card, as we do not need to emulate one in our CI.
        #
        # Finally, while we cannot use `hvf` as an accelerator (as m1 chips do not support nested
        # virtualization, and this runner is already virtualized), we do enable the HVF-premised
        # networking (`vmnet`) for the performance speedup there. Interestingly, it doesn't require
        # `hvf=accel`. This is done by using our `qemu-system-aarch64-vmnet` wrapper instead of
        # `qemu-system-aarch64`.
        #
        # We accomplish all of this with the methodology from
        # [this comment](https://github.com/lima-vm/lima/pull/3173#issuecomment-2623130310).
        QEMU_SYSTEM_AARCH64: "qemu-system-aarch64-vmnet -machine virt -cpu cortex-a76 -m 3G -accel tcg,tb-size=2048 -vga none"
      with:
        set-host: true

    - name: Remove preinstalled Docker
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        docker system prune --all --force

        # GitHub uses an install script from Microsoft, so we run the complimentary uninstall script
        Invoke-WebRequest https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/uninstall-docker-ce.ps1 -OutFile .\uninstall-docker-ce.ps1
        & .\uninstall-docker-ce.ps1 -Force

        # These are defined/installed by the GitHub runner image definition
        # GitHub also adds Docker Compose, but to Docker's directory, causing it to be removed when Docker is
        Remove-Item -LiteralPath C:\Windows\SysWOW64\docker.exe -Force
        Remove-Item -LiteralPath C:\Windows\System32\docker-credential-wincred.exe -Force

    # The preinstalled Docker, and Docker from `setup-docker-action`, do not allow running Linux
    # containers. We manually install `podman` to workaround this. Alternatively, we could install
    # 'Docker Desktop' and run `docker desktop engine use linux`, but `docker desktop` is a
    # pseudo-enterprise product and it isn't worth installing/configuring it compared to installing
    # a more direct solution which behaves as a drop-in replacement to the degree we need it_.
    - name: Install Podman (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Invoke-WebRequest https://github.com/containers/podman/releases/download/v5.7.1/podman-installer-windows-amd64.msi -OutFile podman.msi
        Start-Process -Wait -PassThru 'msiexec' -ArgumentList "/package podman.msi /quiet /log podman-msi.log MACHINE_PROVIDER=wsl ALLUSERS=1"
        Get-Content podman-msi.log

        $env:PATH += ';C:\Program Files\Podman'

        # Start Podman
        podman machine init
        podman machine start

        # Claim `podman` is `docker`, as we expect `docker`
        # Installing to `System32` is gross, but functional and where `docker.exe` was pre-installed
        New-Item -ItemType SymbolicLink -Path 'C:\Windows\System32\docker.exe' -Target (Get-Command podman).Path

    # When cross-compiling to a target architecture, the host still impacts the result. For our
    # runtime, a WASM blob which should be exactly reproducible, we fix the builder to x86-64
    # accordingly. This requires we be able to run a x86-64 userspace.
    - name: Install x64 Qemu for non-x64 Docker
      if: runner.arch != 'X64'
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # 3.7.0
      with:
        platforms: amd64

    # This isn't strictly required. ARM macOS performs very slowly and `buildx` is notably faster.
    - name: Install `buildx`
      if: (runner.os == 'macOS') && (runner.arch == 'ARM64')
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # 3.12.0
      with:
        # This is Docker's default, but `setup-buildx-action` defaults to `docker-container`
        # (for _some_ reason) which means built images won't be loaded into Docker (`--load`) by
        # default. We want that behavior.
        driver: docker
        # We do want this to install over `build` for the drop-in performance gains
        install: true

    # This ensures we have a consistent clean build, there aren't any issues from any version of
    # `docker` we removed before installing our current version, and checks that `docker` was in
    # fact installed and can be successfully called.
    - name: Ensure there's no Docker cache
      shell: bash
      run: docker system prune --all --force
