name: test-dependencies
description: Installs test dependencies for Serai

inputs:
  monero-version:
    description: "Monero version to download and run as a regtest node"
    required: false
    default: v0.18.5.1

  bitcoin-version:
    description: "Bitcoin version to download and run as a regtest node"
    required: false
    default: "31.0"

runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      uses: ./.github/actions/build-dependencies

    - name: Install Anvil
      shell: bash
      run: |
        VERSION=982849d3140c01fd3b72905759581a132df7aa98 # 1.8.1
        cargo +1.97.1 install --git https://github.com/foundry-rs/foundry --rev "$VERSION" --locked anvil

    - name: Run a Monero Regtest Node
      uses: ./.github/actions/monero
      with:
        version: ${{ inputs.monero-version }}

    - name: Run a Bitcoin Regtest Node
      uses: ./.github/actions/bitcoin
      with:
        version: ${{ inputs.bitcoin-version }}
