name: test-dependencies
description: Installs test dependencies for Serai

inputs:
  monero-version:
    description: "Monero version to download and run as a regtest node"
    required: false
    default: v0.18.4.6

  bitcoin-version:
    description: "Bitcoin version to download and run as a regtest node"
    required: false
    default: "31.0"

runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      uses: ./.github/actions/build-dependencies

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # 1.8.0
      with:
        version: 1.7.0 # TODO: f83bad912a9dba7bf0371def1e70bb1896048356 # 1.7.0
        cache: false

    - name: Run a Monero Regtest Node
      uses: ./.github/actions/monero
      with:
        version: ${{ inputs.monero-version }}

    - name: Run a Bitcoin Regtest Node
      uses: ./.github/actions/bitcoin
      with:
        version: ${{ inputs.bitcoin-version }}
