name: test-dependencies
description: Installs test dependencies for Serai

inputs:
  monero-version:
    description: "Monero version to download and run as a regtest node"
    required: false
    default: v0.18.4.6

  bitcoin-version:
    description: "Bitcoin version to download and run as a regtest node"
    required: false
    default: "30.2"

runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      uses: ./.github/actions/build-dependencies

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@50d5a8956f2e319df19e6b57539d7e2acb9f8c1e # 1.5.0
      with:
        version: v1.5.0
        cache: false

    - name: Run a Monero Regtest Node
      uses: ./.github/actions/monero
      with:
        version: ${{ inputs.monero-version }}

    - name: Run a Bitcoin Regtest Node
      uses: ./.github/actions/bitcoin
      with:
        version: ${{ inputs.bitcoin-version }}
