[package]
name = "serai-coins-pallet"
version = "0.1.0"
description = "Coins pallet for Serai"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/coins"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }

sp-core = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false }

frame-support = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false }
frame-system = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false }

serai-abi = { path = "../abi", default-features = false, features = ["substrate"] }
serai-core-pallet = { path = "../core", default-features = false }

sp-io = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false, optional = true }
pallet-timestamp = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false, optional = true }
frame-benchmarking = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false, optional = true }

[dev-dependencies]
rand_core = { version = "0.6", default-features = false, features = ["std"] }

borsh = { version = "1", default-features = false, features = ["std", "derive", "de_strict_order"] }

sp-io = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false, features = ["std"] }

pallet-timestamp = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false, features = ["std"] }

[features]
std = [
  "scale/std",

  "sp-core/std",

  "frame-support/std",
  "frame-system/std",

  "serai-abi/std",
  "serai-core-pallet/std",

  "sp-io?/std",
  "frame-benchmarking?/std",
  "pallet-timestamp?/std",
]

try-runtime = [
  "frame-support/try-runtime",
  "frame-system/try-runtime",

  "serai-abi/try-runtime",
  "serai-core-pallet/try-runtime",
]

runtime-benchmarks = [
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",

  "serai-core-pallet/runtime-benchmarks",

  "dep:sp-io",
  "dep:frame-benchmarking",
  "frame-benchmarking/runtime-benchmarks",
  "dep:pallet-timestamp",
  "pallet-timestamp/runtime-benchmarks",
]

default = ["std"]
