[package]
name = "dkg-evrf"
version = "0.1.0"
description = "Distributed key generation over ff/group"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/crypto/dkg/evrf"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["dkg", "multisig", "threshold", "ff", "group"]
edition = "2021"
rust-version = "1.89"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
thiserror = { version = "2", default-features = false }

rand_core = { version = "0.6", default-features = false }

zeroize = { version = "^1.5", default-features = false, features = ["zeroize_derive"] }

std-shims = { version = "0.1", path = "../../../common/std-shims", default-features = false }

transcript = { package = "flexible-transcript", path = "../../transcript", version = "^0.3.2", default-features = false, features = ["recommended"] }

ciphersuite = { path = "../../ciphersuite", version = "^0.4.1", default-features = false, features = ["alloc"] }
multiexp = { path = "../../multiexp", version = "0.4", default-features = false }

generic-array = { version = "1", default-features = false, features = ["alloc"] }
blake2 = { version = "0.10", default-features = false }
rand_chacha = { version = "0.3", default-features = false }

generalized-bulletproofs = { git = "https://github.com/monero-oxide/monero-oxide", rev = "a6f8797007e768488568b821435cf5006517a962", default-features = false }
ec-divisors = { git = "https://github.com/monero-oxide/monero-oxide", rev = "a6f8797007e768488568b821435cf5006517a962", default-features = false }
generalized-bulletproofs-circuit-abstraction = { git = "https://github.com/monero-oxide/monero-oxide", rev = "a6f8797007e768488568b821435cf5006517a962", default-features = false }
generalized-bulletproofs-ec-gadgets = { git = "https://github.com/monero-oxide/monero-oxide", rev = "a6f8797007e768488568b821435cf5006517a962", default-features = false }

dkg = { path = ".." }

ciphersuite-kp256 = { path = "../../ciphersuite/kp256", default-features = false, optional = true }
secq256k1 = { path = "../../secq256k1", optional = true }
dalek-ff-group = { path = "../../dalek-ff-group", default-features = false, optional = true }
embedwards25519 = { path = "../../embedwards25519", default-features = false, features = ["alloc"], optional = true }

[dev-dependencies]
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
rand = { version = "0.8", default-features = false, features = ["std"] }
ciphersuite = { path = "../../ciphersuite", default-features = false, features = ["std"]  }
embedwards25519 = { path = "../../embedwards25519", default-features = false, features = ["std"] }
dalek-ff-group = { path = "../../dalek-ff-group", default-features = false, features = ["std"] }
generalized-bulletproofs = { git = "https://github.com/monero-oxide/monero-oxide", rev = "a6f8797007e768488568b821435cf5006517a962", features = ["tests"] }
dkg-recovery = { path = "../recovery" }

[features]
std = [
  "thiserror/std",

  "rand_core/std",

  "zeroize/std",
  "std-shims/std",

  "transcript/std",

  "ciphersuite/std",
  "multiexp/std",
  "multiexp/batch",

  "blake2/std",
  "rand_chacha/std",

  "generalized-bulletproofs/std",
  "ec-divisors/std",
  "generalized-bulletproofs-circuit-abstraction/std",
  "generalized-bulletproofs-ec-gadgets/std",

  "dkg/std",

  "ciphersuite-kp256?/std",
  "secq256k1?/std",
  "dalek-ff-group?/std",
  "embedwards25519?/std",
]
secp256k1 = ["ciphersuite-kp256", "secq256k1"]
ed25519 = ["dalek-ff-group", "embedwards25519"]
ristretto = ["dalek-ff-group", "embedwards25519"]
tests = ["rand_core/getrandom"]
default = ["std"]
