[package]
name = "zalloc"
version = "0.1.0"
description = "An allocator which zeroizes all memory on deallocation"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/common/zalloc"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2021"
rust-version = "1.81"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
zeroize = { version = "1.6", default-features = false }

[features]
alloc = ["zeroize/alloc"]
std = ["alloc", "zeroize/std"]
default = ["std"]
allocator = []
