# syntax=docker/dockerfile:1
# check=error=true

# StageX `pallet-rust` as built by `bootstrap.sh`
FROM stagex/pallet-rust AS source

ENV SERAI_RUNTIME_VENDOR=/serai/vendor

ADD patches /serai/patches
ADD common /serai/common
ADD crypto /serai/crypto
ADD networks /serai/networks
ADD message-queue /serai/message-queue
ADD processor /serai/processor
ADD coordinator /serai/coordinator
ADD substrate /serai/substrate
ADD orchestration/Cargo.toml /serai/orchestration/Cargo.toml
ADD orchestration/src /serai/orchestration/src
ADD tests /serai/tests
ADD Cargo.toml /serai
ADD Cargo.lock /serai
ADD AGPL-3.0 /serai

FROM source AS vendor
WORKDIR /serai
RUN <<-'EOF'
  set -eux

  # Fetch the runtime's dependencies
  mkdir .cargo
  RUSTC_BOOTSTRAP=1 cargo vendor --versioned-dirs \
    --manifest-path ./substrate/runtime/Cargo.toml \
    --sync $(rustc --print sysroot)/lib/rustlib/src/rust/library/Cargo.toml \
    $SERAI_RUNTIME_VENDOR > .cargo/config.toml

  # Remove all binary artifacts from the runtime's dependencies
  find $SERAI_RUNTIME_VENDOR -type f ! -name "Cargo.toml" ! -name "*.rs" ! -name "*.json" ! -name "*.md" -delete

  # Remove all checksums as they've already been validated and will no longer match moving forward,
  # since we've mutated the downloaded crates
  grep -v "^checksum =" ./Cargo.lock > ./Cargo.lock.checksumless
  mv ./Cargo.lock.checksumless ./Cargo.lock
  for file in $(find $SERAI_RUNTIME_VENDOR -type f -name ".cargo-checksum.json"); do
    echo "{ \"files\": {} }" > "$file"
  done
EOF

FROM source AS build

WORKDIR /serai

COPY --from=vendor $SERAI_RUNTIME_VENDOR $SERAI_RUNTIME_VENDOR
COPY --from=vendor /serai/.cargo/config.toml /serai/.cargo/config.toml
COPY --from=vendor /serai/Cargo.lock /serai/Cargo.lock

# Build the runtime
RUN --network=none cargo build --frozen --release -p serai-runtime --no-default-features -vv
# Move it to the root
RUN --network=none mv $(find /serai -name serai_runtime.wasm | head -n1) /serai.wasm

# Copy the artifact to its own image which solely exists to further export it
# We build this image from an image with `busybox` so it has basic utilities available within itself
FROM stagex/core-busybox
# Copy the artifact itself
COPY --from=build /serai.wasm /
# By default, copy the artifact to `/volume`, presumably a provided volume
CMD ["cp", "/serai.wasm", "/volume/"]
