[package]
name = "generalized-bulletproofs-circuit-abstraction"
version = "0.1.0"
description = "An abstraction for arithmetic circuits over Generalized Bulletproofs"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/crypto/evrf/circuit-abstraction"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["bulletproofs", "circuit"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
zeroize = { version = "^1.5", default-features = false, features = ["zeroize_derive"] }

ciphersuite = { path = "../../ciphersuite", version = "0.4", default-features = false, features = ["std"] }

generalized-bulletproofs = { path = "../generalized-bulletproofs" }
