[package]
name = "serai-economic-security-pallet"
version = "0.1.0"
description = "Economic Security pallet for Serai"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/economic-security/pallet"
authors = ["Akil Demir <akildemir72@gmail.com>"]
edition = "2021"
rust-version = "1.77"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-machete]
ignored = ["scale", "scale-info"]

[lints]
workspace = true

[dependencies]
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"] }

frame-system = { git = "https://github.com/serai-dex/substrate", default-features = false }
frame-support = { git = "https://github.com/serai-dex/substrate", default-features = false }

dex-pallet = { package = "serai-dex-pallet", path = "../../dex/pallet", default-features = false }
coins-pallet = { package = "serai-coins-pallet", path = "../../coins/pallet", default-features = false }

serai-primitives = { path = "../../primitives", default-features = false }

[features]
std = [
  "scale/std",
  "scale-info/std",

  "frame-system/std",
  "frame-support/std",

  "dex-pallet/std",
  "coins-pallet/std",

  "serai-primitives/std",
]
try-runtime = [] # TODO

default = ["std"]
