# Install ca-certificates
RUN apt install -y ca-certificates

# Switch to a non-root user
RUN useradd --system --create-home --shell /sbin/nologin processor
USER processor

WORKDIR /home/processor

# Copy the Processor binary and relevant license
COPY --from=builder --chown=processsor /serai/bin/serai-processor /bin/
COPY --from=builder --chown=processsor /serai/AGPL-3.0 .

# Run processor
CMD ["serai-processor"]
