name: monero-regtest
description: Spawns a regtest Monero daemon

env:
  version: 0.17.3.2

# Does not take version as an input as this is the source of truth for what
# version to use for Serai, at this time. Could be further modularized
inputs:

# VM state should automatically be an output
outputs:

runs:
  using: "composite"
  steps:
    - name: Monero daemon cache
      id: cache-monerod
      uses: actions/cache@v3
      with:
        path: monerod
        key: monerod-${{ runner.os }}-${{ runner.arch }}-v${{ env.version }}

    - name: Download the Monero Daemon
      if: steps.cache-monerod.outputs.cache-hit != 'true'
      # Calculates OS/ARCH to demonstrate it, yet then locks to linux-x64 due
      # to the contained folder not following the same naming scheme and
      # requiring further expansion not worth doing right now
      run: |
        RUNNER_OS=${{ runner.os }}
        RUNNER_ARCH=${{ runner.arch }}

        RUNNER_OS=${RUNNER_OS,,}
        RUNNER_ARCH=${RUNNER_ARCH,,}

        RUNNER_OS=linux
        RUNNER_ARCH=x64

        FILE=monero-$RUNNER_OS-$RUNNER_ARCH-v${{ env.version }}.tar.bz2
        wget https://downloads.getmonero.org/cli/$FILE
        tar -xvf $FILE

        mv monero-x86_64-linux-gnu-v${{ env.version }}/monerod monerod

    - name: Monero Regtest Daemon
      run: ./monerod --regtest --offline --fixed-difficulty=1 --detach
