[package]
name = "tributary-sdk"
version = "0.1.0"
description = "A micro-blockchain to provide consensus and ordering to P2P communication"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/coordinator/tributary-sdk"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
rust-version = "1.91"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
thiserror = { version = "2", default-features = false, features = ["std"] }

subtle = { version = "^2", default-features = false, features = ["std"] }
zeroize = { version = "^1.5", default-features = false, features = ["std"] }

rand = { version = "0.8", default-features = false, features = ["std"] }

blake2 = { version = "0.11.0-rc.5", default-features = false, features = ["alloc"] }
transcript = { package = "flexible-transcript", path = "../../crypto/transcript", version = "0.3", default-features = false, features = ["std", "recommended"] }

ciphersuite = { path = "../../crypto/ciphersuite", version = "0.4", default-features = false, features = ["std"] }
dalek-ff-group = { path = "../../crypto/dalek-ff-group", default-features = false, features = ["std"] }
schnorr = { package = "schnorr-signatures", path = "../../crypto/schnorr", version = "0.5", default-features = false, features = ["std", "aggregate"] }

hex = { version = "0.4", default-features = false, features = ["std"] }
log = { version = "0.4.4", default-features = false, features = ["std"] }

serai-db = { path = "../../common/db", version = "0.2", default-features = false, features = ["std", "schema"] }

borsh = { version = "1", default-features = false, features = ["std", "derive", "de_strict_order"] }
tendermint = { package = "tendermint-machine", path = "./tendermint", version = "0.3", default-features = false, features = ["std"] }

tokio = { version = "1.4", default-features = false, features = ["sync", "time", "rt"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }

[features]
tests = []
