[package]
name = "serai-tributary-types"
version = "0.1.0"
description = "Tributary validator types for the Serai Coordinator"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/coordinator/tributary/types"
authors = ["Luke Parker <lukeparker5132@gmail.com>", "rafael_xmr <g.pi8ax@slmail.me>"]
keywords = []
edition = "2021"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
borsh = { version = "1", default-features = false, features = ["derive", "de_strict_order"] }

dkg = { path = "../../../crypto/dkg", default-features = false }
std-shims = { path = "../../../common/std-shims", version = "0.1.1", default-features = false }

rand = { version = "0.8", default-features = false, features = ["std", "std_rng"], optional = true }

serai-primitives = { path = "../../../substrate/primitives", default-features = false, features = ["std", "test-helpers"] }

[dev-dependencies]
hex = { version = "0.4", default-features = false, features = ["std"] }
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
serai-env = { path = "../../../common/env", version = "0.1.0", features = ["test-helpers"] }

[features]
std = [
  "borsh/std",
  "dkg/std",
  "std-shims/std",
]
default = ["std"]
test-helpers = ["serai-primitives/test-helpers", "rand"]
