[package]
name = "tendermint-machine"
version = "0.1.0"
description = "An implementation of the Tendermint state machine in Rust"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/tendermint"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[dependencies]
parity-scale-codec = { version = "3.2", features = ["derive"] }

async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt", "sync"] }
