[package]
name = "aurora-engine-modexp"
version = "1.99.99"
description = "Patch to wrap num-bigint"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/patches/ethereum/aurora-engine-modexp"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace]

[dependencies]
num-bigint = { version = "0.4", default-features = false, features = ["std"] }
