[package]
name = "serai-abi"
version = "0.1.0"
description = "ABI for the Serai runtime"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/abi"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
borsh = { version = "1", default-features = false, features = ["derive", "de_strict_order"] }

sp-core = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"], optional = true }
sp-runtime = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false, features = ["serde"], optional = true }
frame-support = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false, optional = true }
frame-system = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false, optional = true }

serai-primitives = { path = "../primitives", version = "0.1", default-features = false }

[dev-dependencies]
rand_core = { version = "0.6", default-features = false, features = ["std"] }

bitvec = { version = "1", default-features = false, features = ["alloc", "std"] }

sp-consensus-babe = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false, features = ["std"] }
sp-consensus-grandpa = { git = "https://github.com/serai-dex/patch-polkadot-sdk", default-features = false, features = ["std"] }

[features]
std = [
  "borsh/std",

  "sp-core/std",

  "scale?/std",
  "sp-runtime?/std",
  "frame-support?/std",
  "frame-system?/std",

  "serai-primitives/std",
]
substrate = ["scale", "sp-runtime", "frame-support", "frame-system", "serai-primitives/scale"]
try-runtime = ["sp-runtime/try-runtime"]
default = ["std"]
