[package]
name = "serai-in-instructions"
version = "0.1.0"
description = "Execute contracts via In Instructions from inherent transactions"
license = "AGPL-3.0-only"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
async-trait = { version = "0.1", optional = true }
thiserror = { version = "1", optional = true }

scale = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

sp-std = { default-features = false, git = "https://github.com/serai-dex/substrate" }
sp-inherents = { default-features = false, git = "https://github.com/serai-dex/substrate" }
sp-runtime = { default-features = false, git = "https://github.com/serai-dex/substrate" }

frame-system = { default-features = false, git = "https://github.com/serai-dex/substrate" }
frame-support = { default-features = false, git = "https://github.com/serai-dex/substrate" }

[features]
std = [
  "async-trait",
  "thiserror",

	"scale/std",
	"scale-info/std",

	"sp-std/std",
	"sp-inherents/std",
	"sp-runtime/std",

  "frame-system/std",
	"frame-support/std",
]
default = ["std"]
