name: build-dependencies
description: Installs build dependencies for Serai

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt update -y
          sudo apt install -y ca-certificates protobuf-compiler libclang-dev
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install protoc
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install protobuf llvm
          HOMEBREW_PREFIX=$(brew --prefix)
          ls $HOMEBREW_PREFIX/opt/llvm/lib | grep "libclang.dylib" # Make sure this installed `libclang`
          echo "DYLD_LIBRARY_PATH=$HOMEBREW_PREFIX/opt/llvm/lib:$DYLD_LIBRARY_PATH" >> "$GITHUB_ENV"
        fi

    - name: Minimal CI
      uses: ./.github/actions/minimal-ci

    - name: Install solc
      shell: bash
      run: |
        cargo install svm-rs --version =0.5.23

        solc_version() {
          # Install the version of `solc` specified in the contracts
          # This also checks the specified version is consistent across contracts
          cat $(find . -name "*.sol") | grep "pragma solidity" | while read -r line; do
            THIS_SOLC_VERSION=$(printf "%s" "$line" | cut -d'^' -f2 | cut -d';' -f1)
            if [ "$SOLC_VERSION" = "" ]; then
              SOLC_VERSION="$THIS_SOLC_VERSION"
              echo $SOLC_VERSION
            fi
            if [ ! "$line" = "pragma solidity ^$SOLC_VERSION;" ]; then
              echo "Inconsistent Solidity requirement in \`.sol\` files"
              exit 1
            fi
          done
        }

        svm install $(solc_version)
        svm use $(solc_version)

    # This is a build dependency, not a test dependency, due to being used to build the runtime
    - name: Install `docker`
      uses: ./.github/actions/docker
