name: build-dependencies
description: Installs build dependencies for Serai

inputs:
  rust-toolchain:
    description: "Rust toolchain to install"
    required: false
    default: stable

  rust-components:
    description: "Rust components to install"
    required: false
    default:

runs:
  using: "composite"
  steps:
    - name: Install solc
      shell: bash
      run: |
        pip3 install solc-select
        solc-select install 0.8.9
        solc-select use 0.8.9

    - name: Install Rust
      uses: ./.github/actions/cached-rust
      with:
        toolchain: ${{ inputs.rust-toolchain }}
        components: ${{ inputs.rust-components }}

    - name: Install WASM toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        target: wasm32-unknown-unknown
