name: build-dependencies
description: Installs build dependencies for Serai

runs:
  using: "composite"
  steps:
    - name: Remove unused packages
      shell: bash
      run: |
        # Ensure the repositories are synced
        sudo apt update -y

        # Actually perform the removals
        sudo apt remove -y "*powershell*" "*nuget*" "*bazel*" "*ansible*" "*terraform*" "*heroku*" "*aws*" azure-cli
        sudo apt remove -y "*yarn*" "*java*" "*kotlin*" "*golang*" "*swift*" "*julia*" "*fortran*" "*android*"
        sudo apt remove -y "*apache2*" "*nginx*" "*firefox*" "*chromium*" "*chrome*" "*edge*"

        sudo apt remove -y --allow-remove-essential -f shim-signed *python3*
        # This removal command requires the prior removals due to unmet dependencies otherwise
        sudo apt remove -y "*qemu*" "*sql*" "*texinfo*" "*imagemagick*"

        # Reinstall python3 as a general dependency of a functional operating system
        sudo apt install -y python3 --fix-missing
      if: runner.os == 'Linux'

    - name: Remove unused packages
      shell: bash
      run: |
        (gem uninstall -aIx) || (exit 0)
        brew uninstall --force "*msbuild*" "*powershell*" "*nuget*" "*bazel*" "*ansible*" "*terraform*" "*heroku*" "*aws*" azure-cli
        brew uninstall --force "*nodejs*" "*npm*" "*yarn*" "*java*" "*kotlin*" "*golang*" "*swift*" "*julia*" "*fortran*" "*android*"
        brew uninstall --force "*apache2*" "*nginx*" "*firefox*" "*chromium*" "*chrome*" "*edge*"
        brew uninstall --force "*qemu*" "*sql*" "*texinfo*" "*imagemagick*"
        brew cleanup
      if: runner.os == 'macOS'

    - name: Install dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install -y ca-certificates protobuf-compiler libclang-dev
        elif [ "$RUNNER_OS" == "Windows" ]; then
          # Use `-gnu` to avoid the installation and licensing headaches of `-msvc`
          rustup set default-host x86_64-pc-windows-gnu
          choco install llvm protoc
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install protobuf llvm
          HOMEBREW_PREFIX=$(brew --prefix)
          [ -d "$HOMEBREW_PREFIX" ]
          ls $HOMEBREW_PREFIX/opt/llvm/lib | grep "libclang.dylib" # Make sure this installed `libclang`
          echo "DYLD_LIBRARY_PATH=$HOMEBREW_PREFIX/opt/llvm/lib:$DYLD_LIBRARY_PATH" >> "$GITHUB_ENV"
        fi

    - name: Install solc
      shell: bash
      run: |
        cargo +1.95.0 install --locked svm-rs --version =0.5.24

        solc_version() {
          # Install the version of `solc` specified in the contracts
          # This also checks the specified version is consistent across contracts
          cat $(find . -name "*.sol") | grep "pragma solidity" | while IFS="\n" read -r line; do
            THIS_SOLC_VERSION=$(printf "%s" "$line" | cut -d'^' -f2 | cut -d'=' -f2 | cut -d';' -f1)
            if [ "$SOLC_VERSION" = "" ]; then
              SOLC_VERSION="$THIS_SOLC_VERSION"
              echo "$SOLC_VERSION"
            fi
            if [ ! "$SOLC_VERSION" = "$THIS_SOLC_VERSION" ]; then
              echo "Inconsistent Solidity requirement in \`.sol\` files"
              exit 1
            fi
          done
        }

        svm install "$(solc_version)"
        svm use "$(solc_version)"

    # This is a build dependency, not a test dependency, due to being used to build the runtime
    - name: Install `docker`
      uses: ./.github/actions/docker

    - name: Update system dependencies
      shell: bash
      run: |
        sudo apt update -y
        sudo apt upgrade -y
        sudo apt autoremove -y
        sudo apt clean -y
      if: runner.os == 'Linux'

    - name: Update system dependencies
      shell: bash
      run: |
        brew upgrade
        rm -rf $(brew --cache)
      if: runner.os == 'macOS'

    - name: Set GitHub CI Environment Variables
      shell: bash
      run: |
        # These tweak the amount of iterations performed as approprtiate for GitHub's CI
        echo 'GITHUB_CI=true' >> "$GITHUB_ENV"
        echo RUSTFLAGS="$RUSTFLAGS --cfg github_ci" >> "$GITHUB_ENV"
        # We always appreciate backtraces in the CI
        echo 'RUST_BACKTRACE=1' >> "$GITHUB_ENV"
