name: build-dependencies
description: Installs build dependencies for Serai

inputs:
  github-token:
    description: "GitHub token to install Protobuf with"
    require: true
    default:

runs:
  using: "composite"
  steps:
    - name: Remove unused packages
      shell: bash
      run: |
        sudo apt remove -y "*msbuild*" "*powershell*" "*nuget*" "*bazel*" "*ansible*" "*terraform*" "*heroku*" "*aws*" azure-cli
        sudo apt remove -y "*nodejs*" "*npm*" "*yarn*" "*java*" "*kotlin*" "*golang*" "*swift*" "*julia*" "*fortran*" "*android*"
        sudo apt remove -y "*apache2*" "*nginx*" "*firefox*" "*chromium*" "*chrome*" "*edge*"
        sudo apt remove -y "*qemu*" "*sql*" "*texinfo*" "*imagemagick*"
        sudo apt autoremove -y
        sudo apt clean
        docker system prune -a --volumes
      if: runner.os == 'Linux'

    - name: Install dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install -y ca-certificates
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install protoc
        fi

    - name: Install Protobuf
      uses: arduino/setup-protoc@a8b67ba40b37d35169e222f3bb352603327985b6
      with:
        repo-token: ${{ inputs.github-token }}
      if: runner.os == 'Linux'

    - name: Install solc
      shell: bash
      run: |
        cargo install svm-rs
        svm install 0.8.16
        svm use 0.8.16

    # - name: Cache Rust
    #   uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43
