name: build-dependencies
description: Installs build dependencies for Serai

inputs:
  github-token:
    description: "GitHub token to install Protobuf with"
    require: true
    default:

  rust-toolchain:
    description: "Rust toolchain to install"
    required: false
    default: stable

  rust-components:
    description: "Rust components to install"
    required: false
    default:

runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-toolchain }}
        components: ${{ inputs.rust-components }}

    - name: Get nightly version to use
      id: nightly
      shell: bash
      run: echo "version=$(cat .github/nightly-version)" >> $GITHUB_OUTPUT

    - name: Install WASM toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.nightly.outputs.version }}
        targets: wasm32-unknown-unknown
