name: bitcoin-regtest
description: Spawns a regtest Bitcoin daemon

inputs:
  version:
    description: "Version to download and run"
    required: false
    default: "31.0"

runs:
  using: "composite"
  steps:
    - name: Bitcoin Daemon Cache
      id: cache-bitcoind
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # 6.1.0
      with:
        path: bitcoin-${{ inputs.version }}
        key: bitcoind-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Download and Extract the Bitcoin Daemon
      if: steps.cache-bitcoind.outputs.cache-hit != 'true'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        OS="${{ runner.os }}"
        ARCH="${{ runner.arch }}"

        OS=$(echo "${OS}" | tr "[:upper:]" "[:lower:]")
        ARCH=$(echo "${ARCH}" | tr "[:upper:]" "[:lower:]")
        EXT="tar.gz"

        if [ "${ARCH}" = "x64" ]; then
          ARCH="x86_64"
        fi

        if [ "${OS}" = "linux" ]; then
          OS="-linux-gnu"
        fi
        if [ "${OS}" = "macos" ]; then
          OS="-apple-darwin"
        fi
        if [ "${OS}" = "windows" ]; then
          ARCH=""
          OS="win64"
          EXT="zip"
        fi

        FILE="bitcoin-${VERSION}-${ARCH}${OS}.${EXT}"

        curl -L "https://bitcoincore.org/bin/bitcoin-core-${VERSION}/${FILE}" -o "${FILE}"

        if [ "${{ runner.os }}" = "Windows" ]; then
          unzip "${FILE}"
          mv $(find . -name "bitcoind*") .
        else
          tar -xf "${FILE}"
          cd "bitcoin-${VERSION}"
          if [ "${{ runner.os }}" = "macOS" ]; then
            sudo mv bin/* /usr/local/bin/
          else
            sudo mv bin/* /usr/bin/
          fi
        fi

    - name: Bitcoin Regtest Daemon
      shell: bash
      run: PATH="${PATH}:$(pwd)" ./orchestration/dev/networks/bitcoin/run.sh -daemon
