name: bitcoin-regtest
description: Spawns a regtest Bitcoin daemon

inputs:
  version:
    description: "Version to download and run"
    required: false
    default: "30.1"

runs:
  using: "composite"
  steps:
    - name: Bitcoin Daemon Cache
      id: cache-bitcoind
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # 4.2.4
      with:
        path: bitcoin*
        key: bitcoind-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Download the Bitcoin Daemon
      if: steps.cache-bitcoind.outputs.cache-hit != 'true'
      shell: bash
      run: |
        OS=${{ runner.os }}
        ARCH=${{ runner.arch }}

        OS=$(echo "$OS" | tr "[:upper:]" "[:lower:]")
        ARCH=$(echo "$ARCH" | tr "[:upper:]" "[:lower:]")
        EXT="tar.gz"

        if [ "$ARCH" = "x64" ]; then
          ARCH="x86_64"
        fi

        if [ "$OS" = "linux" ]; then
          OS="-linux-gnu"
        fi
        if [ "$OS" = "macos" ]; then
          OS="-apple-darwin"
        fi
        if [ "$OS" = "windows" ]; then
          ARCH=""
          OS="win64"
          EXT="zip"
        fi

        FILE=bitcoin-${{ inputs.version }}-$ARCH$OS.$EXT

        wget https://bitcoincore.org/bin/bitcoin-core-${{ inputs.version }}/$FILE
        mv $FILE bitcoin.$EXT

    - name: Extract the Bitcoin Daemon
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          unzip bitcoin.zip
          mv $(find . -name "bitcoind*") .
        else
          tar -xf bitcoin.tar.gz
          cd bitcoin-${{ inputs.version }}
          sudo mv bin/* /usr/bin && sudo mv lib/* /usr/lib
        fi

    - name: Bitcoin Regtest Daemon
      shell: bash
      run: PATH="$PATH:$(pwd)" ./orchestration/dev/networks/bitcoin/run.sh -txindex -daemon
