[package]
name = "serai-runtime"
version = "0.1.0"
description = "Serai's on-chain logic"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/runtime"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-machete]
ignored = ["scale"]

[lints]
workspace = true

[dependencies]
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }

sp-core = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }
sp-session = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }
sp-version = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }
sp-runtime = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }
sp-api = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }

serai-abi = { path = "../abi", default-features = false, features = ["substrate"] }

frame-system = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }
frame-support = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }
frame-executive = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }

pallet-timestamp = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }
pallet-session = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }
pallet-babe = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }
pallet-grandpa = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9", default-features = false }

serai-core-pallet = { path = "../core", default-features = false }
serai-coins-pallet = { path = "../coins", default-features = false }
serai-validator-sets-pallet = { path = "../validator-sets", default-features = false }
serai-signals-pallet = { path = "../signals", default-features = false }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "ef18bfc7029d4a3d7c27e1d0b84da5091628a7d9" }

[features]
std = [
  "scale/std",

  "sp-core/std",
  "sp-session/std",
  "sp-version/std",
  "sp-runtime/std",
  "sp-api/std",

  "serai-abi/std",

  "frame-system/std",
  "frame-support/std",
  "frame-executive/std",

  "pallet-session/std",
  "pallet-babe/std",
  "pallet-grandpa/std",

  "serai-core-pallet/std",
  "serai-coins-pallet/std",
  "serai-validator-sets-pallet/std",
  "serai-signals-pallet/std",
]

try-runtime = [
  "sp-runtime/try-runtime",

  "serai-abi/try-runtime",

  "frame-system/try-runtime",
  "frame-support/try-runtime",
  "frame-executive/try-runtime",

  "pallet-session/try-runtime",
  "pallet-babe/try-runtime",
  "pallet-grandpa/try-runtime",

  "serai-core-pallet/try-runtime",
  "serai-coins-pallet/try-runtime",
  "serai-validator-sets-pallet/try-runtime",
  "serai-signals-pallet/try-runtime",
]

runtime-benchmarks = [
  "sp-runtime/runtime-benchmarks",

  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",

  "pallet-babe/runtime-benchmarks",
  "pallet-grandpa/runtime-benchmarks",

  "pallet-session/runtime-benchmarks",
  "serai-core-pallet/runtime-benchmarks",
  "serai-coins-pallet/runtime-benchmarks",
  "serai-validator-sets-pallet/runtime-benchmarks",
  "serai-signals-pallet/runtime-benchmarks",
]

default = ["std"]
