[package]
name = "in-instructions-client"
version = "0.1.0"
description = "Package In Instructions into inherent transactions"
license = "AGPL-3.0-only"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-trait = "0.1"

scale = { package = "parity-scale-codec", version = "3", features = ["derive", "max-encoded-len"] }

jsonrpsee-core = "0.16"
jsonrpsee-http-client = "0.16"

sp-inherents = { git = "https://github.com/serai-dex/substrate" }

in-instructions-pallet = { path = "../pallet" }
