[package]
name = "serai-signals-pallet"
version = "0.1.0"
description = "Signals pallet"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/signals"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-machete]
ignored = ["scale"]

[lints]
workspace = true

[dependencies]
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }

sp-core = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "71fa60b900c8ad068f1b9ce8100508506377fbf5", default-features = false }

frame-system = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "71fa60b900c8ad068f1b9ce8100508506377fbf5", default-features = false }
frame-support = { git = "https://github.com/serai-dex/patch-polkadot-sdk", rev = "71fa60b900c8ad068f1b9ce8100508506377fbf5", default-features = false }

serai-abi = { path = "../abi", default-features = false, features = ["substrate"] }

serai-core-pallet = { path = "../core", default-features = false }
serai-validator-sets-pallet = { path = "../validator-sets", default-features = false }

[features]
std = [
  "scale/std",

  "sp-core/std",

  "frame-system/std",
  "frame-support/std",

  "serai-abi/std",

  "serai-core-pallet/std",
  "serai-validator-sets-pallet/std",
]

runtime-benchmarks = [
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",

  "serai-core-pallet/runtime-benchmarks",
  "serai-validator-sets-pallet/runtime-benchmarks",
]

try-runtime = [
  "frame-system/try-runtime",
  "frame-support/try-runtime",

  "serai-abi/try-runtime",

  "serai-core-pallet/try-runtime",
  "serai-validator-sets-pallet/try-runtime",
]

default = ["std"]
