[package]
name = "tokens-primitives"
version = "0.1.0"
description = "Serai tokens primitives"
license = "MIT"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
zeroize = { version = "^1.5", features = ["derive"], optional = true }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"] }

serde = { version = "1", features = ["derive"], optional = true }

serai-primitives = { path = "../../serai/primitives", default-features = false }

[dev-dependencies]
sp-runtime = { git = "https://github.com/serai-dex/substrate", default-features = false }

[features]
std = ["zeroize", "scale/std", "scale-info/std", "serde", "sp-runtime/std", "serai-primitives/std"]
default = ["std"]
