[package]
name = "serai-client-monero"
version = "0.1.0"
description = "A client for the Serai network's Monero functionality"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/client/monero"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["serai", "monero"]
edition = "2021"
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
borsh = { version = "1", default-features = false, features = ["std"] }

serai-primitives = { path = "../../primitives", version = "0.1", default-features = false, features = ["std"] }

ciphersuite = { path = "../../../crypto/ciphersuite", default-features = false, features = ["std"] }
dalek-ff-group = { path = "../../../crypto/dalek-ff-group", default-features = false, features = ["std"] }
monero-address = { git = "https://github.com/monero-oxide/monero-oxide", rev = "030c60974f0f0306849c1795bca854a3bbb757b4", version = "0.1.0", default-features = false, features = ["std"] }
