[package]
name = "option-ext"
version = "0.2.99"
description = "Non-MPL option-ext with only the API necessary for directories"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/patches/option-ext"
edition = "2021"
rust-version = "1.56"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace]
