[package]
name = "alloy-hardforks"
version = "0.2.99"
description = "Patch to a minimal alternative implementation"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/patches/ethereum/alloy-hardforks"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace]

[features]
serde = []
