[package]
name = "serai-client"
version = "0.1.0"
description = "Client library for the Serai network"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/client"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["serai"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
thiserror = { version = "1", optional = true }

scale = { package = "parity-scale-codec", version = "3" }
scale-info = { version = "2", optional = true }

serai-runtime = { path = "../../runtime", version = "0.1" }

subxt = { version = "0.25", optional = true }

bitcoin = { version = "0.29", optional = true }

ciphersuite = { path = "../../../crypto/ciphersuite", version = "0.2", optional = true }
monero-serai = { path = "../../../coins/monero", version = "0.1.3-alpha", optional = true }

[features]
serai = ["thiserror", "scale-info", "subxt"]

coins = []
bitcoin = ["coins", "dep:bitcoin"]
monero = ["coins", "ciphersuite/ed25519", "monero-serai"]

# Assumes the default usage is to use Serai as a DEX, which doesn't actually
# require connecting to a Serai node
default = ["bitcoin", "monero"]

[dev-dependencies]
lazy_static = "1"

rand_core = "0.6"

tokio = "1"

jsonrpsee-server = "0.16"
