[package]
name = "serai-client"
version = "0.1.0"
description = "Client library for the Serai network"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/client"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["serai"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
thiserror = "1"

serde = { version = "1", features = ["derive"] }

scale = { package = "parity-scale-codec", version = "3" }
scale-info = "2"
scale-value = "0.6"

sp-core = { git = "https://github.com/serai-dex/substrate", version = "7" }

serai-primitives = { path = "../primitives", version = "0.1" }
serai-runtime = { path = "../../runtime", version = "0.1" }

subxt = "0.25"

[dev-dependencies]
lazy_static = "1"

tokio = "1"

jsonrpsee-server = "0.16"
