[package]
name = "serai-shim-rpc"
version = "0.1.0"
description = "A bespoke shim RPC node for testing Serai RPC clients without a real chain"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/tests/shim-rpc"
authors = ["Luke Parker <lukeparker5132@gmail.com>", "rafael_xmr <g.pi8ax@slmail.me>"]
edition = "2024"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-machete]
ignored = ["serai-primitives"]

[lints]
workspace = true

[dependencies]
hex = { version = "0.4", default-features = false, features = ["std"] }
borsh = { version = "1", default-features = false, features = ["std", "derive"] }

rand_core = { version = "0.6", default-features = false }
blake2 = { version = "0.11", default-features = false }
schnorrkel = { version = "0.11", default-features = false, features = ["std"] }

serai-primitives = { path = "../../substrate/primitives", features = ["std", "test-helpers"] }
serai-abi = { path = "../../substrate/abi", default-features = false, features = ["std"] }

serde = { version = "1", default-features = false, features = ["std"] }
jsonrpsee = { version = "0.24", default-features = false, features = ["server"] }
tokio = { version = "1", default-features = false }

[dev-dependencies]
serai-client-serai = { path = "../../substrate/client/serai" }
