[package]
name = "serai-liquidity-tokens-pallet"
version = "0.1.0"
description = "liquidity tokens pallet for Serai"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/substrate/liquidity-tokens/pallet"
authors = ["Akil Demir <aeg_asd@hotmail.com>"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
parity-scale-codec = { version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"] }

frame-system = { git = "https://github.com/serai-dex/substrate", default-features = false }
frame-support = { git = "https://github.com/serai-dex/substrate", default-features = false }

sp-core = { git = "https://github.com/serai-dex/substrate", default-features = false }
sp-std = { git = "https://github.com/serai-dex/substrate", default-features = false }

dex-primitives = { package = "serai-dex-primitives", path = "../../dex/primitives", default-features = false }

serai-primitives = { path = "../../primitives", default-features = false }

[features]
std = [
  "frame-system/std",
  "frame-support/std",

  "sp-core/std",
  "sp-std/std",

  "dex-primitives/std",

  "serai-primitives/std",
]

runtime-benchmarks = [
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
]

default = ["std"]
