[package]
name = "serai-coordinator-tributary"
version = "0.1.0"
description = "The Tributary used by the Serai Coordinator"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/coordinator/tributary"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2021"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
zeroize = { version = "^1.5", default-features = false, features = ["std"] }
rand_core = { version = "0.6", default-features = false, features = ["std"] }

borsh = { version = "1", default-features = false, features = ["std", "derive", "de_strict_order"] }

blake2 = { version = "0.11.0-rc.5", default-features = false, features = ["alloc"] }
ciphersuite = { path = "../../crypto/ciphersuite", default-features = false, features = ["std"] }
dalek-ff-group = { path = "../../crypto/dalek-ff-group", default-features = false, features = ["std"] }
dkg = { path = "../../crypto/dkg", default-features = false, features = ["std"] }
schnorr = { package = "schnorr-signatures", path = "../../crypto/schnorr", default-features = false, features = ["std"] }

serai-primitives = { path = "../../substrate/primitives", default-features = false, features = ["std", "test-helpers"] }

serai-db = { path = "../../common/db" }
serai-task = { path = "../../common/task", version = "0.1" }

tributary-sdk = { path = "../tributary-sdk" }

serai-cosign-types = { path = "../cosign/types" }
serai-coordinator-substrate = { path = "../substrate" }

messages = { package = "serai-processor-messages", path = "../../processor/messages" }

serai-env = { path = "../../secret-store/env", version = "0.1.0" }

[dev-dependencies]
rand = { version = "0.8", default-features = false, features = ["std"] }
rand_chacha = { version = "0.3", default-features = false, features = ["std"] }

tendermint = { package = "tendermint-machine", path = "../tributary-sdk/tendermint" }
tributary-sdk = { path = "../tributary-sdk", features = ["tests"] }

tokio = { version = "1", default-features = false, features = ["rt", "time", "macros", "rt-multi-thread"] }

serai-task = { path = "../../common/task", features = ["test-helpers"] }
serai-substrate-tests = { path = "../../tests/substrate" }

[features]
longer-reattempts = []
