[package]
name = "tendermint-machine"
version = "0.2.0"
description = "An implementation of the Tendermint state machine in Rust"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/coordinator/tributary-sdk/tendermint"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
rust-version = "1.91"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
pin-project-lite = { version = "0.2", default-features = false }

borsh = { version = "1", default-features = false, features = ["derive", "de_strict_order"], optional = true }

async-channel = { version = "2", default-features = false, optional = true }
serai-db = { path = "../../../common/db", version = "0.2", default-features = false, features = ["std", "schema"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["sync", "time", "rt-multi-thread", "macros"] }

[features]
alloc = ["borsh"]
std = ["alloc", "borsh/std", "async-channel", "serai-db"]
default = ["std"]
