[package]
name = "serai-task"
version = "0.1.0"
description = "A task schema for Serai services"
license = "AGPL-3.0-only"
repository = "https://github.com/serai-dex/serai/tree/develop/common/task"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2021"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
serai-env = { path = "../env", version = "0.1.0" }
tokio = { version = "1", default-features = false, features = ["macros", "sync", "time"] }
futures = { version = "0.3", default-features = false, features = ["std"] }
serai-client-serai = { path = "../../substrate/client/serai" }
serai-mock-rpc = { path = "../../tests/mock-serai-rpc" }
serai-db = { path = "../db" }

[features]
test-helpers = []
alloc = []
default = ["alloc"]
