[package]
name = "getrandom"
version = "0.3.99"
description = "Updates to the latest version"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/patches/getrandom"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = []
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace]

[dependencies]
getrandom = { version = "0.4", default-features = false }

[features]
std = ["getrandom/std"]
wasm_js = ["getrandom/wasm_js"]
