[package]
name = "std-shims"
version = "0.1.5"
description = "A series of shims for std to make alloc more feasible"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/common/std-shims"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["nostd", "no_std", "alloc", "io"]
edition = "2021"
rust-version = "1.85"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
rustversion = { version = "1", default-features = false }
spin = { version = "0.12", default-features = false, features = ["use_ticket_mutex", "fair_mutex", "once", "lazylock"] }
hashbrown = { version = "0.17", default-features = false, features = ["default-hasher", "inline-more"], optional = true }

[features]
alloc = ["dep:hashbrown"]
std = ["alloc", "spin/std"]
default = ["std"]
