[package]
name = "bulletproofs-plus"
version = "0.1.0"
description = "Bulletproofs+ implementation"
license = "MIT"
repository = "https://github.com/kayabaNerve/serai/tree/snarks/crypto/bulletproofs-plus"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["ciphersuite", "ff", "group"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
rand_core = { version = "0.6", default-features = false }

zeroize = { version = "^1.5", default-features = false, features = ["zeroize_derive"] }
subtle = { version = "^2.4", default-features = false }

transcript = { package = "flexible-transcript", path = "../transcript", version = "0.3" }

crypto-bigint = { version = "0.5", default-features = false }
pasta_curves = { version = "0.5", default-features = false, features = ["bits", "alloc"], git = "https://github.com/kayabaNerve/pasta_curves.git", optional = true }
multiexp = { path = "../multiexp", default-features = false, features = ["batch"] }
ciphersuite = { path = "../ciphersuite", default-features = false }

ecip = { path = "../ecip" }

[dev-dependencies]
rand_core = { version = "0.6", features = ["getrandom"] }

transcript = { package = "flexible-transcript", path = "../transcript", features = ["recommended"] }

pasta_curves = { version = "0.5", default-features = false, features = ["bits", "alloc"], git = "https://github.com/kayabaNerve/pasta_curves.git" }
ciphersuite = { path = "../ciphersuite", features = ["ristretto", "pasta"] }
ecip = { path = "../ecip", features = ["pasta"] }

[features]
tests = ["pasta_curves"]
