[package]
name = "ff-group-tests"
version = "0.13.2"
description = "A collection of sanity tests for implementors of ff/group APIs"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/crypto/ff-group-tests"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["ff", "group", "ecc"]
edition = "2021"
rust-version = "1.81"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-machete]
ignored = ["tap"]

[lints]
workspace = true

[dependencies]
rand_core = { version = "0.6", default-features = false }

subtle = { version = "2.5", default-features = false, features = ["std"] }

# `ff` requires `bitvec` requires `wyz 0.5.0` which requires `tap 1.0.1` but only specifies `tap 1.0.0`
tap = { version = "1.0.1", default-features = false }
ff = { version = "0.13", default-features = false, features = ["std", "bits"] }
group = { version = "0.13", default-features = false, features = ["alloc"] }

[dev-dependencies]
rand_core = { version = "0.6", default-features = false, features = ["std"] }
k256 = { version = "0.13.1", default-features = false, features = ["std", "arithmetic", "bits"] }
p256 = { version = "0.13.1", default-features = false, features = ["std", "arithmetic", "bits"] }
