replicaCount: 1

image:
  repository: serai-dev-monero
  pullPolicy: IfNotPresent
  tag: "latest"
  ports:
    - name: p2p
      containerPort: 18080
      protocol: TCP
    - name: rpc
      containerPort: 18081
      protocol: TCP
  volumeMounts:
    - mountPath: /scripts
      name: configmap-volume
  args:
    - bash 
    - /scripts/entry-dev.sh
    
volumes:
  - configMap:
      defaultMode: 420
      name: configmap
    name: configmap-volume

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: ClusterIP
  ports:
    - name: p2p
      port: 18080
      targetPort: p2p
      protocol: TCP
    - name: rpc
      port: 18081
      targetPort: rpc
      protocol: TCP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
