name: common/ Tests

on:
  push:
    branches:
      - develop
    paths:
      - "common/**"

  pull_request:
    paths:
      - "common/**"

  workflow_dispatch:

jobs:
  test-common:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-26-intel, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run Tests
        run: |
          cargo test --all-features \
            -p std-shims \
            -p zalloc \
            -p patchable-async-sleep \
            -p serai-db \
            -p serai-env \
            -p serai-task \
            -p simple-request
