name: crypto/ Tests
permissions: {}

on:
  push:
    branches:
      - develop
      - next
    paths:
      - "common/**"
      - "crypto/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"

  workflow_dispatch:

jobs:
  test-crypto:
    name: Test `crypto/` crates

    strategy:
      matrix:
        os: [ubuntu-latest, macos-26-intel, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
        with:
          persist-credentials: false

      - name: Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run Tests
        shell: bash
        run: |
          find ./crypto -name "Cargo.toml" | while IFS="\n" read -r manifest; do
            cargo test --all-features --manifest-path $manifest
          done
