name: crypto/ Tests

on:
  push:
    branches:
      - develop
      - next-polkadot-sdk
    paths:
      - "common/**"
      - "crypto/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"

  workflow_dispatch:

jobs:
  test-crypto:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-26-intel, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run Tests
        shell: bash
        run: |
          find ./crypto -name "Cargo.toml" | while IFS="\n" read -r manifest; do
            cargo test --all-features --manifest-path $manifest
          done
