name: Daily Deny Check
permissions: {}

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deny:
    name: Run `cargo deny`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false

      - name: Install `cargo deny`
        run: cargo +1.97.1 install --locked cargo-deny --version =0.20.2

      - name: Run `cargo deny`
        run: cargo deny -L error --all-features check --hide-inclusion-graph
