name: Full Stack Tests
permissions: {}

on:
  push:
    branches:
      - develop

  pull_request:

  workflow_dispatch:

jobs:
  test-full-stack:
    name: e2e tests for the full stack (`tests/full-stack`)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false

      - name: Install Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run Full Stack Docker tests
        run: cargo test --all-features -p serai-full-stack-tests
