name: Test Libraries on Redox
permissions: {}

on:
  push:
    branches:
      - develop
      - next
    paths:
      - "common/**"
      - "crypto/**"
      - "coordinator/tributary-sdk/tendermint/*"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"
      - "coordinator/tributary-sdk/tendermint/*"

  workflow_dispatch:

jobs:
  test-redox:
    name: Test Libraries on Redox
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false

      - name: Install QEMU
        run: sudo apt update -y && sudo apt upgrade -y && sudo apt install -y qemu-system-x86 jq

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Tests for Libraries on Redoxer
        shell: bash
        run: |
          export GITHUB_CI=true
          export RUST_BACKTRACE=1

          ACCEL="kvm"
          if [ ! -w /dev/kvm ]; then
            # Don't use `kvm` which isn't supported here
            ACCEL="tcg"
          fi
          # Add an explicit audio device as else `audiod` fails to initialize and the booting fails
          export REDOXER_QEMU_ARGS="-smp $(nproc) -accel $ACCEL -audio none,model=ac97"
          export TARGET=x86_64-unknown-redox

          cargo +1.97.1 install --locked redoxer --version =0.2.63
          redoxer toolchain

          CRATES=$(find ./common ./crypto ./coordinator/tributary-sdk/tendermint -name "Cargo.toml")
          echo "$CRATES" | while IFS="\n" read -r manifest; do
            FEATURES="--all-features"
            if [ "$manifest" = "./common/db/Cargo.toml" ]; then
              FEATURES=""
            fi

            # Build the tests, without running them, and extract their absolute paths via `jq`
            TESTS=$(redoxer test -- "$FEATURES" --manifest-path "$manifest" --no-run --message-format=json | jq -r '.executable | select(. != null)')
            # Convert our filesystem's absolute paths to what will be Redox's absolute paths
            TESTS=$(echo "$TESTS" | sed s/$(pwd | sed s/'\/'/'\\\/'/g)//g | sed s/'^'/'\/root'/g)
            echo "$TESTS" | while IFS="\n" read -r test; do
              redoxer exec --folder '.:/root' "$test"
            done
          done
