name: Test Libraries on Redox

on:
  push:
    branches:
      - develop
    paths:
      - "common/**"
      - "crypto/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"

  workflow_dispatch:

jobs:
  test-redox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Run Tests for Libraries on Redoxer
        run: |
          cargo +1.93 install redoxer --version =0.2.62
          redoxer toolchain
          GITHUB_CI=true RUST_BACKTRACE=1 redoxer test -- --all-features \
            -p std-shims \
            -p zalloc \
            -p patchable-async-sleep \
            -p simple-request \
            -p flexible-transcript \
            -p ff-group-tests \
            -p dalek-ff-group \
            -p minimal-ed448 \
            -p ciphersuite \
            -p ciphersuite-kp256 \
            -p multiexp \
            -p schnorr-signatures \
            -p prime-field \
            -p short-weierstrass \
            -p secq256k1 \
            -p embedwards25519 \
            -p dkg \
            -p dkg-recovery \
            -p dkg-dealer \
            -p dkg-musig \
            -p dkg-evrf \
            -p modular-frost \
            -p frost-schnorrkel
