name: Test Libraries on Redox
permissions: {}

on:
  push:
    branches:
      - develop
    paths:
      - "common/**"
      - "crypto/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"

  workflow_dispatch:

jobs:
  test-redox:
    name: Test Libraries on Redox
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
        with:
          persist-credentials: false

      - name: Install QEMU
        run: sudo apt update -y && sudo apt upgrade -y && sudo apt install -y qemu-system-x86

      - name: Run Tests for Libraries on Redoxer
        shell: bash
        run: |
          cargo +1.96.0 install --locked redoxer --version =0.2.62
          TARGET=x86_64-unknown-redox redoxer toolchain

          find ./common ./crypto -name "Cargo.toml" | while IFS="\n" read -r manifest; do
            if [ "$manifest" = "./common/db/Cargo.toml" ]; then
              continue
            fi
            GITHUB_CI=true RUST_BACKTRACE=1 redoxer test -- --all-features --manifest-path $manifest
          done
