name: Lint
permissions: {}

on:
  push:
    branches:
      - develop
      - next
  pull_request:
  workflow_dispatch:

jobs:
  clippy:
    name: cargo clippy
    strategy:
      # Run these sequentially so we don't get the same syntax error from each entry of the matrix
      max-parallel: 1
      matrix:
        os: [macos-26-intel]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false

      - name: Get nightly version to use
        id: nightly
        shell: bash
        run: |
          # Ensure `nightly-version` only contains numbers and dashes
          [ $(grep -v "^[0-9-]*$" .github/nightly-version | wc -l || true) -eq 0 ]
          echo "NIGHTLY_VERSION=nightly-$(cat .github/nightly-version)" >> "$GITHUB_ENV"

      - name: Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Install nightly rust
        shell: bash
        run: rustup toolchain install "${NIGHTLY_VERSION}" --profile minimal --component clippy --component rust-src

      - name: Run Clippy
        shell: bash
        run: |
          # stable Rust
          cargo clippy --locked --all-features --all-targets -- -D warnings
          # Check a few variations of `serai-primitives`, `serai-abi`
          cargo clippy --locked --no-default-features --all-targets -p serai-primitives -- -D warnings
          cargo clippy --locked --all-targets -p serai-primitives -- -D warnings
          cargo clippy --locked --no-default-features --all-targets -p serai-abi -- -D warnings
          cargo clippy --locked --all-targets -p serai-abi -- -D warnings

          # nightly Rust
          cp ./Cargo.toml ./Cargo.toml.bak
          sed s/'# TODO: `-Zcargo-lints`: '//g ./Cargo.toml > ./Cargo.toml.cargo-lints
          mv ./Cargo.toml.cargo-lints ./Cargo.toml
          cargo +"${NIGHTLY_VERSION}" clippy --locked -Zcargo-lints --all-features --all-targets -- -D warnings
          cargo +"${NIGHTLY_VERSION}" clippy --locked -Zcargo-lints --no-default-features --all-targets -p serai-primitives -- -D warnings
          cargo +"${NIGHTLY_VERSION}" clippy --locked -Zcargo-lints --all-targets -p serai-primitives -- -D warnings
          cargo +"${NIGHTLY_VERSION}" clippy --locked -Zcargo-lints --no-default-features --all-targets -p serai-abi -- -D warnings
          cargo +"${NIGHTLY_VERSION}" clippy --locked -Zcargo-lints --all-targets -p serai-abi -- -D warnings
          mv ./Cargo.toml.bak ./Cargo.toml

      - name: Verify `pallet::hooks` is unused
        shell: bash
        run: |
          FAILURES=$(
            find ./substrate -name "*.rs" | while IFS="\n" read -r file; do
              hooks=$(grep -F "pallet::hooks" "$file" | grep -v -F "serai-core-pallet: allow" | wc -l || true)
              if [ $hooks -ne 0 ]; then
                echo "\`pallet::hooks\` (without \`serai-core-pallet: allow\`) found in $file"
              fi
            done
          )
          if [ ! "$FAILURES" = "" ]; then
            echo "$FAILURES"
            exit 1
          fi

      # Check the Git index didn't change as a result of the build process
      - name: Check the Git index is unmodified
        shell: bash
        run: |
          # Add all files so any untracked files are also considered in the difference
          git add .
          # Check there's no difference
          [ $(git diff HEAD | wc -l) -eq 0 ]

