name: Message Queue Tests

on:
  push:
    branches:
      - develop
      - next
    paths:
      - "common/**"
      - "crypto/**"
      - "message-queue/**"
      - "orchestration/**"
      - "tests/docker/**"
      - "tests/message-queue/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"
      - "message-queue/**"
      - "orchestration/**"
      - "tests/docker/**"
      - "tests/message-queue/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Install Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run message-queue Docker tests
        run: cargo test --all-features -p serai-message-queue-tests
