name: Message Queue Tests

on:
  push:
    branches:
      - develop
    paths:
      - "common/**"
      - "crypto/**"
      - "message-queue/**"
      - "orchestration/**"
      - "tests/docker/**"
      - "tests/message-queue/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"
      - "message-queue/**"
      - "orchestration/**"
      - "tests/docker/**"
      - "tests/message-queue/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Install Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run message-queue Docker tests
        run: cd tests/message-queue && GITHUB_CI=true RUST_BACKTRACE=1 cargo test
