name: mini/ Tests

on:
  push:
    branches:
      - develop
    paths:
      - "mini/**"

  pull_request:
    paths:
      - "mini/**"

  workflow_dispatch:

jobs:
  test-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run Tests
        run: GITHUB_CI=true RUST_BACKTRACE=1 cargo test --all-features -p mini-serai
