name: Monthly Nightly Update
permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update:
    name: Update the nightly version of Rust used to this month's
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
        with:
          persist-credentials: false
          submodules: "recursive"

      - name: Write nightly version
        shell: bash
        run: echo $(date +"%Y-%m"-01) > .github/nightly-version

      - name: Create the commit
        shell: bash
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

          git checkout -b $(date +"nightly-%Y-%m")

          git add .github/nightly-version
          git commit -m "Update nightly"
          git push -u origin $(date +"nightly-%Y-%m")

      - name: Pull Request
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # 9.0.0
        with:
          script: |
            const { repo, owner } = context.repo;

            const result = await github.rest.pulls.create({
              title: (new Date()).toLocaleString(
                false,
                { month: "long", year: "numeric" }
              ) + " - Rust Nightly Update",
              owner,
              repo,
              head: "nightly-" + (new Date()).toISOString().split("-").splice(0, 2).join("-"),
              base: "develop",
              body: "PR auto-generated by a GitHub workflow."
            });

            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ["improvement"]
            });
