name: networks/ Tests

on:
  push:
    branches:
      - develop
    paths:
      - "common/**"
      - "crypto/**"
      - "networks/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"
      - "networks/**"

  workflow_dispatch:

jobs:
  test-networks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies

      - name: Run Tests
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --all-features \
            -p bitcoin-serai \
            -p build-solidity-contracts \
            -p ethereum-schnorr-contract \
            -p alloy-simple-request-transport \
            -p serai-ethereum-relayer \
