name: networks/ Tests
permissions: {}

on:
  push:
    branches:
      - develop
      - next
    paths:
      - "common/**"
      - "crypto/**"
      - "networks/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"
      - "networks/**"

  workflow_dispatch:

jobs:
  test-bitcoin:
    name: Test `networks/bitcoin` crates

    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-26.04, macos-26-intel, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false

      - name: Install Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run a Bitcoin Regtest Node
        uses: ./.github/actions/bitcoin
        with:
          version: ${{ inputs.bitcoin-version }}

      - name: Run Tests
        shell: bash
        run: |
          find ./networks/bitcoin -name "Cargo.toml" | while IFS="\n" read -r manifest; do
            cargo test --all-features --manifest-path "$manifest"
          done

  test-ethereum:
    name: Test `networks/ethereum` crates

    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-26.04, macos-26-intel, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false

      - name: Install Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Install Anvil
        shell: bash
        run: |
          VERSION=cae51ad458f6abb64852b7709eb784352429825d # 1.8.3
          cargo +1.98.1 install --git https://github.com/foundry-rs/foundry --rev "$VERSION" --locked anvil

      - name: Run Tests
        shell: bash
        run: |
          find ./networks/ethereum -name "Cargo.toml" | while IFS="\n" read -r manifest; do
            cargo test --all-features --manifest-path "$manifest"
          done
