name: Processor Tests
permissions: {}

on:
  push:
    branches:
      - develop
    paths:
      - "common/**"
      - "crypto/**"
      - "networks/**"
      - "message-queue/**"
      - "processor/**"
      - "orchestration/**"
      - "tests/docker/**"
      - "tests/processor/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"
      - "networks/**"
      - "message-queue/**"
      - "processor/**"
      - "orchestration/**"
      - "tests/docker/**"
      - "tests/processor/**"

  workflow_dispatch:

jobs:
  test-processor:
    name: e2e tests for the processor (`tests/processor`)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
        with:
          persist-credentials: false

      - name: Install Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run processor Docker tests
        run: cargo test --all-features -p serai-processor-tests
