name: Tests

on:
  push:
    branches:
      - develop
      - next
    paths:
      - "common/**"
      - "crypto/**"
      - "networks/**"
      - "message-queue/**"
      - "processor/**"
      - "coordinator/**"
      - "substrate/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"
      - "networks/**"
      - "message-queue/**"
      - "processor/**"
      - "coordinator/**"
      - "substrate/**"

  workflow_dispatch:

jobs:
  test-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies

      - name: Run Tests
        run: |
          cargo test --all-features -p serai-message-queue
          find ./processor -name "Cargo.toml" | while IFS="\n" read -r manifest; do
            cargo test --all-features --manifest-path $manifest
          done
          find ./coordinator -name "Cargo.toml" | while IFS="\n" read -r manifest; do
            cargo test --all-features --manifest-path $manifest
          done
          cargo test --all-features -p serai-orchestrator
          cargo test --all-features -p serai-shim-rpc
          cargo test --all-features -p serai-docker-tests

  test-substrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run Tests
        shell: bash
        run: |
          find ./substrate -name "Cargo.toml" ! -path "*client*" | while IFS="\n" read -r manifest; do
            cargo test --all-features --manifest-path $manifest
          done
          cargo test --all-features -p serai-substrate-tests

  test-serai-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run Tests
        shell: bash
        run: |
          find ./substrate -name "Cargo.toml" -path "*client*" | while IFS="\n" read -r manifest; do
            cargo test --all-features --manifest-path $manifest
          done
